### ISSUE TITLE
Blackscreen

### ISSUE THREAD

**Issue by PPTGYukine** [pokemon-sots/pokemon-sots-issues#107]
**Beschreibe den Bug**
Ich bekam ein Blackscreen nachdem ich ein Kampf gemacht habe und einmal als ich den Raum gewechselt habe.

**Reproduzieren**

1. Nach einem Kampf oder als ich den Raum verlassen habe
2. Der Screen bleibt ein Blackscreen und das Spiel gibt von sich aus ungesunde Geräusche

**Erwartetes Verhalten**
Na ja ist glaub logisch was hier erwartet wird... sollte nicht passieren :'D

**Screenshots**
*Wenn möglich und nötig, Screenshots die den Fehler zeigen.*
![SotS Bug #2](https://user-images.githubusercontent.com/65416767/82116697-fcfdae80-976b-11ea-87a0-aad24cbc5422.png)

**Verwendeter Emulator / Hardware**
VBA-M 

**Zusätzliche Information**
Wüsste ich ehrlich gesagt grade nicht

**Comment by ipatix** [comment]
Duplicate 108
