### ISSUE TITLE
Blackscreen VBA-M

### ISSUE THREAD

**Issue by 4Reddy** [pokemon-sots/pokemon-sots-issues#108]
**Beschreibe den Bug**
Blackscreen durch wechseln von maps.

**Reproduzieren**
*Schritte, um den Bug auszulösen*
1. Starte das Spiel mit VBA-M
2. Wechsle maps (zum bewussten herbei führen solange wechseln bis es passiert)
3. Der Bildschirm färbt sich schwarz, stößt glitch sounds aus und das spiel stürzt ab

**Erwartetes Verhalten**
Kein abstürzten des spieles

**Screenshots**
(Muss leider so sein, ich kann einfach keine gif aus dem video erstellen) 
https://discord.com/channels/499637031744438272/689454286605910118/711160241668227103

**Verwendeter Emulator / Hardware**
VBA-M Version 2.1.4 auf Windows 10

**Zusätzliche Information**

**Comment by ipatix** [comment]
Ein potentieller Fix gefunden, muss aber noch getestet werden.

**Comment by ipatix** [comment]
9fb8271b83a031b9ed226c407ec972399b4fe073 fixt es vermutlich.
