### ISSUE TITLE
Weiblicher Held hat falschen Namen

### ISSUE THREAD

**Issue by 4Reddy** [pokemon-sots/pokemon-sots-issues#11]
*Bitte fülle dieses Template aus, und lösche **Beschreibe den Bug**
Weiblicher held heißt Emma obwohl sie in meinen Fall Bunny heißt

**Reproduzieren**
1. Triggere in Hesperia das gespräch mit Vater und seinen freund bezüglich der brücke die eingebrochen ist
2. Beim Dialog bezüglich dass der Spieler der anführer ist und nicht das andere kind bekommt der Spieler eine eigene dialog box mit "... ... ..."
Dort trägt sie aber den falschen Namen und heißt Emma und nicht in meinem fall Bunny

**Erwartetes Verhalten**
Dort sollte Bunny stehen

**Screenshots**
![IMG_20200511_004136](https://user-images.githubusercontent.com/65133519/81512419-c1548600-9320-11ea-95ef-a03951b3cfe0.jpg)

**Verwendeter Emulator / Hardware**
JohnGBA auf Android

**Zusätzliche Information**
/

**Comment by SBird1337** [comment]
iirc passiert das an ein paar stellen im Spiel, wenn der Mugshot des gespielten geschlechts kommt
