### ISSUE TITLE
Premierball wird nach einem Fang zu Luxusball

### ISSUE THREAD

**Issue by Seki-blip** [pokemon-sots/pokemon-sots-issues#114]
**Beschreibe den Bug**
Fängt man ein Pokémon mit einem Premierball, wird dieser nach dem Fang zu einem Luxusball.

**Reproduzieren**
1. Fange ein Pokémon mit einem Premierball
2. Das Pokémon befindet sich nun in einem Luxusball

**Erwartetes Verhalten**
Fängt man ein Pokémon mit einem Premierball, sollte dieser ein Premierball bleiben.

**Screenshots**
![Pokemon SotS-4](https://user-images.githubusercontent.com/65471537/82132877-f52e2080-97e4-11ea-8b2d-a9ee6cd9536d.png)
Fangversuch mit Premierball

![Pokemon SotS-5](https://user-images.githubusercontent.com/65471537/82132879-f8291100-97e4-11ea-9591-be4b3b590588.png)
Im Bericht wird ein Luxusball angezeigt

![Pokemon SotS-6](https://user-images.githubusercontent.com/65471537/82132880-fa8b6b00-97e4-11ea-83ef-352ab1b98a5c.png)
Auch, wenn man das Pokémon in den Kampf schickt, wird ein Luxusball angezeigt.

**Verwendeter Emulator / Hardware**
mGBA 0.8.1

**Zusätzliche Information**
Untersucht man die Savefile mit PKHex, sieht man, dass es sich nicht nur um einen Anzeigefehler handelt. Laut PKHex befindet sich das gefangene Pokémon in einem Luxusball.

**Comment by ipatix** [comment]
Wird vermutlich nicht mehr in die Hotfixes für die Alpha 1 schaffen.

**Comment by Dragonflysots** [comment]
#fix upstream
