### ISSUE TITLE
Schlaf Statuseffekt wird sofort entfernt

### ISSUE THREAD

**Issue by ThoreW95** [pokemon-sots/pokemon-sots-issues#117]
Beschreibung:
Schlaf Statuseffekt wird im aktuellen Kampf sofort entfernt (Pokemon wacht auf)

Reproduzieren:
1. Das eigene Pokemon einschläfern lassen
2. Im nächsten Zug das gegnerische Pokemon angreifen (nicht auswechseln!)

Erwartetes Verhalten: 
Das Pokemon sollte nicht sofort aufwachen

Emulator:
N3DS mit der Virtual Console

**Comment by Dragonflysots** [comment]
@ThoreW95 Tritt das jedesmal auf? Weil grundsätzlich kann ein Pokémon in der selben Runde wieder aufwachen.

**Comment by ThoreW95** [comment]
bisher immer. Mein Pokemon war langsamer als der Gegner, der Gegner schläfert ihn ein und mein Pokemon wacht sofort wieder auf und greift in der gleichen Runde an. Das wirkt nicht normal auf mich.

**Comment by Dragonflysots** [comment]
Welches Pokémon? Auf ALLE deinen Pokémon?

**Comment by Dragonflysots** [comment]
@ThoreW95

**Comment by ThoreW95** [comment]
Der Statuseffekt? Der wird nur auf mein angreifendes Pokemon angewendet.

**Comment by Dragonflysots** [comment]
@ThoreW95 Ne ich meinte eher ob das mit der Fähigkeit deines Pokémon zusammenhängt. Welches Pokémon hast du bzw. hast du nur eins bei dir?

**Comment by ThoreW95** [comment]
Das war ein Zubat mit Konzentrator. Hat damit nichts zu tun. Ganz zu anfang mit meinem Geckarbor hatte ich das auch

**Comment by SBird1337** [comment]
Das ist eine Änderung, die vmtl Upstream geschehen muss, daher wird sie es vmtl. nicht in den Hotfix schaffen.
