### ISSUE TITLE
Bauernfrau will 800$ für die Kuhmuh milch, jedoch gibst du ihr nur 500$.

### ISSUE THREAD

**Issue by Kite2810** [pokemon-sots/pokemon-sots-issues#119]
**Beschreibe den Bug**
Wenn man mit der Bauernhof Frau redet um Kuhmuhmilch zu kaufen, bezahlt man mit 500$ anstelle von den eigentlichen 800$.

**Reproduzieren**
*Schritte, um den Bug auszulösen*
1. Gehe nach `Sylviria City`
2. Rede mit dem auf dem Bild zu sehenden NPC
3. Man verliert 500$ anstelle 800$.

**Erwartetes Verhalten**
Natürlich das man wirklich 800$ bezahlt und nicht 500$. :P

**Screenshots**
![20200517_183622](https://user-images.githubusercontent.com/65502641/82154355-8b0d8e00-986d-11ea-9607-2e9884fc7ef6.jpg)

**Verwendeter Emulator / Hardware**
mGBA/Windows, AMD Athlon II x4, 4x 3,0GHz, Nvidia GT9500, 6GB RAM.

**Comment by Dragonflysots** [comment]
Das ist kein Bug, sondern bewusst so eingestellt.
