### ISSUE TITLE
Hohes Gras Animation fehlt auf dem Hesperiapfad

### ISSUE THREAD

**Issue by KyteArvensis** [pokemon-sots/pokemon-sots-issues#123]
**Beschreibe den Bug**
Bewegt man sich auf dem Hesperiapfad durchs hohe Gras, wird über dem Spielersprite kein Gras angezeigt.

**Reproduzieren**
1. Gehe nach `Hesperiapfad`
2. Durch das hohe Gras bewegen

**Erwartetes Verhalten**
Ähnlich wie beim Stehen im hohen Gras sollte auch bei Bewegung Gras über dem Spielersprite angezeigt werden.

**Screenshots**
![Pokemon SotS-2](https://user-images.githubusercontent.com/65471537/82158323-6b835f00-9887-11ea-8717-816519e180d3.png)

**Verwendeter Emulator / Hardware**
mGBA 0.8.1

**Zusätzliche Information**
Keine

**Comment by Dragonflysots** [comment]
![Pokemon Smaragd (D)-0](https://user-images.githubusercontent.com/27623565/82158871-dda97300-988a-11ea-8bf4-a5fab1030696.png)
 
Das ist im Original nicht anders, so schnell kann man sowas nicht reagieren, da es eine bruchtel Sekunde ist.
