### ISSUE TITLE
Spielersprite wird über Türrahmen angezeigt

### ISSUE THREAD

**Issue by KyteArvensis** [pokemon-sots/pokemon-sots-issues#125]
**Beschreibe den Bug**
Geht man durch eine Tür, wird der Sprite des Spielers über dem Türrahmen angezeigt.

**Reproduzieren**
1. Durch eine Tür ein Gebäude betreten
2. Der Spielersprite wird über dem Türrahmen angezeigt

**Erwartetes Verhalten**
Der Spielersprite sollte unter dem Türrahmen angezeigt werden.

**Screenshots**
![Pokemon SotS-4](https://user-images.githubusercontent.com/65471537/82159431-46461f00-988e-11ea-9029-0f4310b54728.png)
![Pokemon SotS-5](https://user-images.githubusercontent.com/65471537/82159432-47774c00-988e-11ea-911f-2e9ef047d652.png)

**Verwendeter Emulator / Hardware**
mGBA 0.8.1

**Zusätzliche Information**
Im Originalspiel ist das ebenfalls so, daher weiß ich nicht, ob es technisch überhaupt möglich ist, den Spielersprite unter Türrahmen anzuzeigen.

**Comment by Dragonflysots** [comment]
Das kann nicht wirklich gefixt werden. Das ist aber auch hier ein Bruchteil einer Sekunde. Solche Sachen sind auf den ersten Anscheint vllt. leicht zu fixen, aber doch recht kompliziert im Code.
