### ISSUE TITLE
Fehlende Kollision im Haus nördlich der Treppen in Hesperia

### ISSUE THREAD

**Issue by KyteArvensis** [pokemon-sots/pokemon-sots-issues#129]
**Beschreibe den Bug**
Im Haus nördlich der Treppen in Hesperia kann man sich direkt vor den Fernseher stellen. Das "Fernseher-Script" triggert nur, wenn man ein Feld vom Fernseher entfernt steht.
Im Haus des Protagonisten kann man die drei Felder direkt vor dem Fernseher nicht betreten.

**Reproduzieren**
1. Gehe nach `Hesperia`
2. Gehe in das Haus nördlich der Treppen
3. Vor den Fernseher stellen

**Erwartetes Verhalten**
Ähnlich wie im Haus des Protagonisten sollte es vermutlich nicht möglich sein, sich direkt vor den Fernseher zu stellen.

**Screenshots**
![Pokemon SotS-0](https://user-images.githubusercontent.com/65471537/82160823-3cc1b480-9898-11ea-8964-5303535dbac2.png)
Das Fernsehr-Script ein Feld vom Fernseher entfernt

![Pokemon SotS-1](https://user-images.githubusercontent.com/65471537/82160834-4cd99400-9898-11ea-8e0f-559094d27a76.png)
Aber man kann sich direkt vor den Fernsehr stellen und dort das Fernsehr-Script nicht mehr triggern.

**Verwendeter Emulator / Hardware**
mGBA 0.8.1

**Zusätzliche Information**
Keine

**Comment by Dragonflysots** [comment]
Screenhot 2 wäre korrekt.

**Comment by Dragonflysots** [comment]
Achso, verstehe jetzt was du meinst ok.

**Comment by KyteArvensis** [comment]
Ich wollte gerade nochmal nachfragen, ob das wirklich so sein sollte, da sich die Fernsehr-Scripts ja auch ein Feld vor dem Fernsehr befinden.

**Comment by Dragonflysots** [comment]
Ne ist sehs auch ist gerade gefixt.^^

**Comment by KyteArvensis** [comment]
Nice. Viel Spaß noch beim... vermutlich nicht schlafen, denn das ist für Menschen :D
Gute Nacht.

**Comment by Dragonflysots** [comment]
Haha, danke. xD Naja Danke fürs testen/spielen.^^:D
