### ISSUE TITLE
Verwirrte Pokemon verletzen sich nur selber

### ISSUE THREAD

**Issue by ThoreW95** [pokemon-sots/pokemon-sots-issues#131]
Beschreibung
Verwirrte Pokemon verletzen sich nur selber.

Reproduzieren
1. Pokemon verwirren (bzw verwirren lassen)
2. Die Runden abwarten und das Verhalten beobachten

Erwartetes Verhalten
Mit einer 50% Wahrscheinlichkeit soll das Pokemon normal Angreifen

Verwendeter Emulator / Hardware
N3DS mit VC

Zusätzliche Information
Beobachtet in 20+ Kämpfen mit Konfustrahl/Superschall. Eigenes Pokemon war ein Golbat/Zubat mit Konzentrator. Heilung von der Verwirrung ist möglich, innerhalb von 2-5 Runden ist das Pokemon nicht mehr verwirrt

**Comment by SBird1337** [comment]
Wie auch schon #117 ist das vmtl. ein Fehler, der in einem Upstream branch gefixt werden muss, und ich kann nicht versprechen, dass es der Fix in den Alpha 1.1.1 Hotfix schaffen wird.
