### ISSUE TITLE
Acupressure freeze

### ISSUE THREAD

**Issue by duelistkind** [pokemon-sots/pokemon-sots-issues#133]
**Describe the Bug**
Acupressure freezes the game either because it tries to assign attack or defense or because it can't do that and so the move should fail but can't.
**Reproduce**
*Steps to reproduce*
1. Get into a battle
2. Keep using acupressure
3. The game freezes but music still plays
**Expected Behavior**
The move should raise physical stats or fail.

**Screenshots**
*If applicable, screenshots that show the bug.*

**Used Emulator / Hardware**
Myboy on Android

**Misc. Information**

**Comment by SBird1337** [comment]
This is probably fixed by DizzyEggg/pokeemerald#381

**Comment by Dragonflysots** [comment]
#fix upstream
