### ISSUE TITLE
Tippfehler William nach der Hesperiahöhle

### ISSUE THREAD

**Issue by Seki-blip** [pokemon-sots/pokemon-sots-issues#134]
**Beschreibe den Bug**
Im Gespräch nach der Hesperiahöhle ist "Menge" kleingeschrieben. 

**Reproduzieren**
1. Verlasse `Hesperiahöhle` zum ersten Mal in Richtung `Östliche Reberaberge`
2. Eine Unterhaltung triggert
3. Der Tippfehler erscheint im Verlauf des Gesprächs 

**Erwartetes Verhalten**
"Menge" großgeschrieben

**Screenshots**
![IMG_20200521_195035](https://user-images.githubusercontent.com/65471537/82590175-8d3d5880-9b9d-11ea-9ac1-c795bc90e987.jpg)

**Verwendeter Emulator / Hardware**
DSi, gbarunner2 via TWLMenu++, sollte hier aber keinen Unterschied machen 

**Zusätzliche Information**
Keine

**Comment by Dragonflysots** [comment]
#fix neue texte
