### ISSUE TITLE
Ruine der Wächter nach Einsturz betretbar

### ISSUE THREAD

**Issue by Seki-blip** [pokemon-sots/pokemon-sots-issues#135]
**Beschreibe den Bug**
Die Ruine der Wächter in den östlichen Reberabergen lässt sich nach dem Einsturz betreten.

**Reproduzieren**
1. Neues Spiel starten
2. Bis nach dem Einsturz der `Ruine der Wächter` spielen 
3. Zurück in die `Ruine der Wächter` gehen 

**Erwartetes Verhalten**
Die heruntergefallenen Steine sollten einen davon abhalten zurück in die Ruine zu gehen. 

**Screenshots**
Nicht nötig

**Verwendeter Emulator / Hardware**
DSi, gbarunner2 via TWLMenu++, sollte hier allerdings keinen Unterschied machen

**Zusätzliche Information**
Keine

**Comment by Dragonflysots** [comment]
#fix with new scripts
