### ISSUE TITLE
Incorrect location name, stones and missigno.

### ISSUE THREAD

**Issue by B-Dragon20** [pokemon-sots/pokemon-sots-issues#137]
I was using the MyBoy, with the english version, the archive doesn't specific if it's 1.0 or 1.1(sorry). I found 3 bugs.

1. In the first Gym when you go up or down in the stairs appears "Southern Island".

2. After the first Gym, when you need to explore further the forest, when you put the jewels in the altar(i choose the Blue jewel) instead appear the jewel appear the sprite of the character (for me appears the boy and i selected the boy, but i don't know if this changes if you select the girl) running on the altar.

3. I used Sweet Scent outside of battle with a oddish and a combee in the ruins of the guardians (i think that's the name) and instead of a combee or a oddish appear when you use the move appeared a missigno (the ball with an "?" mark).

Hope that this help.

**Comment by Dragonflysots** [comment]
#fix new script
