### ISSUE TITLE
Wuffels Entwicklung bei Nacht nicht vorhanden!

### ISSUE THREAD

**Issue by Kite2810** [pokemon-sots/pokemon-sots-issues#138]
wenn man wuffels auf level 25 bringt bei Nacht, bekommt man trotzdem die
Entwicklung die eigentlich nur zu tag auftauchen sollte. 

Wie auf dem screenshot zu erkennen ist es Nacht. die entwicklung zog sich um ca. 23:39 Uhr zu.

gespielt wurde version 1.1.1 DE auf den mGBA, Windows 10 pro.

![image](https://user-images.githubusercontent.com/65502641/90447388-7ac2b480-e0e3-11ea-93ec-3ce72cd0f249.png)

**Comment by Dragonflysots** [comment]
#fix with evolutionsupdate
