### ISSUE TITLE
Mit Premierball gefangende Pokemon, haben falschen bzw. Fehlerhaften Sprite. (Der Ball Sprite im Bericht)

### ISSUE THREAD

**Issue by Kite2810** [pokemon-sots/pokemon-sots-issues#139]
Wird das Pokémon mit einem Premierball gefangen, so ist im Bericht des gefangenden Pokémon ein Fehlerhafter Sprite des Pokeballs zu erkennen.

Sollte so nicht sein, sondern Der richtige Sprite vom Premierball.

![Pokemon Sovereign of the Skies - 1 1 1 - DE -](https://user-images.githubusercontent.com/65502641/122282885-3747fb00-ceec-11eb-87b6-64b042bf3be0.png)

**Comment by SBird1337** [comment]
duplicate of #114
