### ISSUE TITLE
Reference to player as 'player' and save file

### ISSUE THREAD

**Issue by DuskStrikes** [pokemon-sots/pokemon-sots-issues#140]
I found two bugs. Both bugs are minor:

1. At the city where we get the first pokemon, before we get it, if I try going outside the city to the left or right, I get blocked from going, as I am supposed to get the first pokemon. The text refers to me as 'player' rather than my name, which in this case was Zuko.

2. When I was saving the file, all text on the text bar below while saving was another language (German, I believe). This only stays during the save file time.

Steps to reproduce:

First bug:

1. Start the game, leave the school.
2. Complete the side quest from the npc at the ground in front of school entrance, the side quest being to fetch some documents from the school for the npc as he is lazy from the white locker on the first floor, to the left.
3. Leave the school premise, go to the city.
4. Talk to every npc on the way.
5. Go to the left or right of the city, and try to exit the city.
6. You will get a message from your brother/sister, telling you that you should not go there.
7. In that message, the player is referred to as 'player'

Second bug:

1. Save the file from the in game menu.
2. The proceeding text is English, but the language is German.

Used Emulator: John GBAC

**Comment by Dragonflysots** [comment]
#fix with textupdates
