### ISSUE TITLE
Small Pokédex bug + some feedback

### ISSUE THREAD

**Issue by Jaizu** [pokemon-sots/pokemon-sots-issues#141]
**Describe the Bug**
Weight and Height strings are not translated in the English version,

**Reproduce**
Catch an unregistered Pokémon/Use the Pokédex

**Used Emulator / Hardware**
Original GBA.

Not sure if this is the correct place, but some suggestions about the Pokédex:
Minor:
Let me scroll up/down when I'm watching a mon page.
Add back the Area location
Big:
Add a stat page of some sort to get more info about the mon, maybe just base stats or what not.

**Comment by SBird1337** [comment]
it's probably fine, I added an enhancement tag. There's some enhancements planned for the dex anyways, but idk if it will make it into the next release or not. There's also enhancements/additions planned for the upcoming "pokenav" to mitigate the "don't know where to catch X" problem a bit.

**Comment by SBird1337** [comment]
The translation part of this was fixed, we will consider the enhancements posted internally :)
