### ISSUE TITLE
Spiel Absturz bei Anklicken von Spind

### ISSUE THREAD

**Issue by 4Reddy** [pokemon-sots/pokemon-sots-issues#143]
**Beschreibe den Bug**
*Spind angeklickt, das Spiel ist hängen geblieben (Bild da, Ton aus, Tasten Reagieren nicht mehr)*

**Reproduzieren**
*Schritte, um den Bug auszulösen*
1. Starte das Spiel
2. Direkt am Start wo man seine Figur steuern kann habe ich den linken Spind angeklickt
3. das Spiel stürzt ab (Bild da, Ton aus, Tasten Reagieren nicht mehr)

**Erwartetes Verhalten**
*Das Spiel sollte nicht abstürzten.*

**Screenshots**
*![Spiel absturz](https://user-images.githubusercontent.com/65133519/132505033-c48b4dc4-d324-4f3b-8e1a-8b93ab0db069.jpeg)*

**Verwendeter Emulator / Hardware**
*My Boy! (bezahlt) - Xiaomi Redmi Note 9 Pro - Android 11 - MIUI 12.0.4*

**Comment by SBird1337** [comment]
probably due to debug information, was fixed in an internal update
