### ISSUE TITLE
German leftover on opening screen

### ISSUE THREAD

**Issue by Bassoonian** [pokemon-sots/pokemon-sots-issues#145]
**Describe the Bug**
The opening screen shows "startet".

**Reproduce**
Boot up the game.

**Expected Behavior**
Presumably supposed to be replaced with "started" or something along those lines.

**Screenshots**
<img width="918" alt="image" src="https://user-images.githubusercontent.com/16993385/132507838-4c2b261d-3851-4866-a405-5eea19a1e8bb.png">

**Comment by Dragonflysots** [comment]
fixed
