### ISSUE TITLE
Fehlende Textbox (Schiedsrichter Pkmn Kampf schule)

### ISSUE THREAD

**Issue by 4Reddy** [pokemon-sots/pokemon-sots-issues#150]
**Beschreibe den Bug**
*Eine fehlende Textbox bei einem NPC*

**Reproduzieren**
*Schritte, um den Bug auszulösen*
1. Gehe in die Schule zu beginn
2. ab mit dir in das letzt Stockwerk
3. Gehe zum Pokemon Kampf zwischen Natu und Azurill und spreche den Schiedsrichter an

**Erwartetes Verhalten**
*Ich würde mir eine Textbox erwarten. Kann mich auch täuschen und für ihn wurde (noch) keine geplant*

**Screenshots**
*![WhatsApp Image 2021-09-08 at 14 32 37](https://user-images.githubusercontent.com/65133519/132509985-c5fd942d-2537-40f1-a5c8-887531194656.jpeg)*

**Verwendeter Emulator / Hardware**
*My Boy! (bezahlt) - Xiaomi Redmi Note 9 Pro - Android 11 - MIUI 12.0.4*

**Comment by SBird1337** [comment]
could not reproduce
