### ISSUE TITLE
Clock is drawn above Y/N box

### ISSUE THREAD

**Issue by Bassoonian** [pokemon-sots/pokemon-sots-issues#156]
**Describe the Bug**
See title

**Reproduce**
Try to set the clock at the start of the game

**Expected Behavior**
The Y/N box should be drawn above

**Screenshots**
<img width="944" alt="image" src="https://user-images.githubusercontent.com/16993385/132510713-785fb946-420a-40ea-9b16-a83322e9f19c.png">

**Comment by SBird1337** [comment]
fixed internally
