### ISSUE TITLE
Inconsistent capitalisation

### ISSUE THREAD

**Issue by Bassoonian** [pokemon-sots/pokemon-sots-issues#157]
The capitalisation in the game is inconsistent, with the opening menu having NEW GAME and OPTION, as well as the OPTION menu being in all capitals. It is only after the player has given their name that they find out the rest of the game is not in all caps, potentially leaving them stuck with a fully capitalised name. Other (potential) inconsistencies include caps in CLOSE BAG but Normal Bag Pockets.

**Comment by SBird1337** [comment]
If you manage to catch one of these a screenshot would be very appreciated s.t. I can see the context of where decapitalization has not yet occured.

**Comment by Dragonflysots** [comment]
#fix
