### ISSUE TITLE
Nicht logischer Text

### ISSUE THREAD

**Issue by 4Reddy** [pokemon-sots/pokemon-sots-issues#165]
**Beschreibe den Bug**
*Text macht keinen Sinn*

**Reproduzieren**
1. Gehe nach `Hesperia`
2. Gehe in das Haus hinterste Haus (das bei der Brücke (die kaputt ist)
3. Sprich den Fernseher an

**Erwartetes Verhalten**
*Der Junge spielt auf der Konsole aber trotzdem läuft dort eine Serie. Ich weiß, vermutlich wird jeder Fernseher eher die gleiche Textbox bekommen, aber hier wird halt nicht ferngesehen sondern gespielt*

**Screenshots**
*![WhatsApp Image 2021-09-08 at 18 43 16](https://user-images.githubusercontent.com/65133519/132559396-e3aa547f-18b9-4d6d-af90-ebec79277bda.jpeg)*

**Verwendeter Emulator / Hardware**
*My Boy! (bezahlt) - Xiaomi Redmi Note 9 Pro - Android 11 - MIUI 12.0.4*

**Comment by SBird1337** [comment]
idk if this will be wontfix or not

**Comment by Dragonflysots** [comment]
das ist kinderkaka haha
