### ISSUE TITLE
1. Pokecenter Npc's mit gleichem Dialog

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#174]
**Beschreibe den Bug**
Im 1. Pokecenter haben 4 Npc's den selben Dialog

**Reproduzieren**
1. Betrete das 1. Pokecenter.
2. Sprich mit allen Npc's außer dem Wanderer

**Erwartetes Verhalten**
Unterschiedliche Dialoge

**Screenshots**
[Dialog 1](https://youscreen.de/qhycygbfa01.jpg)
[Dialog 2](https://youscreen.de/glgbpvlxm65.jpg)
[Dialog 3](https://youscreen.de/vvleqpfin15.jpg)
[Dialog 4](https://youscreen.de/bbulhamue81.jpg)

**Verwendeter Emulator / Hardware**
VBA-M 2.1.4

**Comment by Dragonflysots** [comment]
fixed
