### ISSUE TITLE
Rechtschreibfehler bei dem Blondschopf

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#18]
**Beschreibe den Bug**
Das Wort "Mann" ist hier an dieser Stelle mit zwei "n" geschrieben. 

**Reproduzieren**
1. Laufe nach dem Gespräch des Spielers in das 1. OG.
2. Rede mit dem auf dem Bild zu sehenden blonden NPC
3. Das Wort "Mann" ist hier mit zwei "n" geschrieben.

**Erwartetes Verhalten**
Korrekte Rechtschreibung

**Screenshots**
![Rechtschreibfehler4](https://user-images.githubusercontent.com/65140155/81515798-fd461600-9335-11ea-8ac7-fac92aecc4d4.JPG)

**Verwendeter Emulator / Hardware**
mGBA 0.8.1

**Zusätzliche Information**
n/a

**Comment by SBird1337** [comment]
Bin mir grade nicht sicher, ob man das nicht zumindest so schreiben kann - Die Schreibweise mit einen `n` ist aber wsl. den meisten eher bekannt.

**Comment by xLiviusx** [comment]
Wenn der Npc direkt den Spieler ansprechen würde, dann ja. Dennoch wäre das dann ja mit dem weiblichen Protagonisten falsch.
