### ISSUE TITLE
Debug Menü

### ISSUE THREAD

**Issue by 4Reddy** [pokemon-sots/pokemon-sots-issues#191]
**Beschreibe den Bug**
*Das Debug Menü lässt sich durch eine Tastenkombination aufrufen.*

**Reproduzieren**
*Schritte, um den Bug auszulösen*
1. Drücke L+R+Start+Select während eines Kampfes
2. Das Debug Menü öffnet sich

**Erwartetes Verhalten**
*Kein Debug Menü*

**Screenshots**
*![Screenshot_2021-09-08-23-43-03-175_com fastemulator gba](https://user-images.githubusercontent.com/65133519/132642902-d07acfde-9a2a-4e11-888e-f59e538a3411.jpg)*

**Verwendeter Emulator / Hardware**
*My Boy! (bezahlt) - Xiaomi Redmi Note 9 Pro - Android 11 - MIUI 12.0.4*

**Comment by SBird1337** [comment]
fixed internally
