### ISSUE TITLE
Rechtschreibfehler nachdem Team Tundra beide Seelengefäße an sich genommen hat

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#203]
**Beschreibe den Bug**
Einstürzen wurde hier mit "tz" geschrieben was falsch ist. Es wird nur mit "z" geschrieben.

**Reproduzieren**
1. Bekämpfe Team Tundra
2. Nachdem Team Tundra beide Seelengefäße zu sich genommen hat
3. Triggere das Gespräch mit Noel

**Erwartetes Verhalten**
Keine Rechtschreibfehler

**Screenshots**
![Rechtschreibfehler 5](https://user-images.githubusercontent.com/65140155/132736669-a24cacf3-e342-4af5-b6d8-9246e38c4019.jpg)

**Verwendeter Emulator / Hardware**
mGBA 0.9.2

**Comment by SBird1337** [comment]
fixed internally
