### ISSUE TITLE
Falscher Mugshot nachdem die Wächter uns befreit haben

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#204]
**Beschreibe den Bug**
Aiden oder William erklären den Kindern ihre neue wichtige Aufgabe. Jedoch wird hier der Mugshot von Emma (und eventuell von Noel gezeigt - je nachdem ob man den männlichen oder weiblichen Protagonisten spielt) verwendet, sowie der Name vom Protagonisten.

**Reproduzieren**
1. Nachdem die Wächter uns befreit haben
2. Triggere das Gespräch mit Aiden oder William
3. Der Mugshot von Emma sowie Name wird gezeigt

**Erwartetes Verhalten**
Einheitliche Mugshots

**Screenshots**
![Mugshot 1](https://user-images.githubusercontent.com/65140155/132739131-38dff81f-6122-4ae3-8a7f-4cfbd80e4aeb.jpg)

**Verwendeter Emulator / Hardware**
mGBA 0.9.2

**Comment by Dragonflysots** [comment]
fix
