### ISSUE TITLE
Font falsch

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#22]
**Beschreibe den Bug**
Der letzte Satz der älteren Dame hat eine andere Font als normalerweise.

**Reproduzieren**
1. Gehe von der Trainerschule aus nach Carun City.
2. Laufe in das Haus links neben der Bank.
3. Der Font des letzten Satzes ist falsch.

**Erwartetes Verhalten**
Einheitliche Font.

**Screenshots**
![Font falsch](https://user-images.githubusercontent.com/65140155/81517658-e4d8fa00-933b-11ea-90ca-820eb72702ce.JPG)

**Verwendeter Emulator / Hardware**
mGBA ver. 0.8.1

**Zusätzliche Information**
n/a

**Comment by Dragonflysots** [comment]
Das ist kein Bug, sondern so gewollt. Eine Art Flüsterstimme

**Comment by xLiviusx** [comment]
Oh dann, entschuldige. :)

**Comment by Dragonflysots** [comment]
Kein Problem.^^
