### ISSUE TITLE
Vorschlag: Pokenav Icons beschriften

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#222]
Vielleicht könnte man die Icons beschriften im Pokenav. Hätte anfangs zum Beispiel nicht gewusst, dass das "Buch" ein Logbuch sein soll oder oben die zwei Wegweiser, dass das die Map sein soll.

![Vorschlag 1](https://user-images.githubusercontent.com/65140155/132768847-0288c489-e59e-4d4f-8e46-c84eb3f729c6.jpg)

**Comment by Dragonflysots** [comment]
Hier könnte man oben links oder unten links einen Schriftzug reinladen.

**Comment by Dragonflysots** [comment]
Würde ich aber dann für die nächste Version machen, nehmen wir auf ins Wekan Board

**Comment by Dragonflysots** [comment]
ist im wekan
