### ISSUE TITLE
Quest namens Geister! wird nicht im Logbuch erfasst

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#226]
**Beschreibe den Bug**
Nach erhalt der neuen Quest "Geister!" steht sie nicht im Logbuch.

**Reproduzieren**
1. Gehe nach dem beenden des Baumes des Lebens nach Sylviria City
2. Beende das Gespräch mit Evelyn und Noah/Emma
3. Öffne das Logbuch

**Erwartetes Verhalten**
Erfassung aller erhaltenen Quests

**Screenshots**
![Bug 4](https://user-images.githubusercontent.com/65140155/132772620-43246464-e301-41f2-8ba9-116cc0e37653.jpg)

**Verwendeter Emulator / Hardware**
mGBA 0.9.2

**Comment by Dragonflysots** [comment]
fixed
