### ISSUE TITLE
Layerfehler beim Heilstein

### ISSUE THREAD

**Issue by xydragonxy** [pokemon-sots/pokemon-sots-issues#227]
**Beschreibe den Bug**
Layerfehler beim Heilstein

**Reproduzieren**
Wenn man ins schimmern des Heilsteins von unten geht überdeckt man das leuchten, kommt man von oben überdeckt das leuchten den Charackter

**Erwartetes Verhalten**
Entweder das Leuchten bleibt über dem dem Char egal in welche Richtung oder unter dem Char ( weiß nicht wie es gewollt ist) 

**Screenshots**
![Layerfehler beim Leuchten](https://user-images.githubusercontent.com/65260349/132860370-e5d523ed-3a26-4a64-9a3d-1bf9f945b37d.PNG)

**Verwendeter Emulator / Hardware**
Vba-M 2.1.4

**Comment by Dragonflysots** [comment]
Das ist nicht fixbar, da es sich hier um ein NPC handelt und diese man so nicht weiteres handeln kann.
