### ISSUE TITLE
Fehlende Textbox

### ISSUE THREAD

**Issue by xydragonxy** [pokemon-sots/pokemon-sots-issues#229]
**Beschreibe den Bug**
Fehlende Textboxen bei Regalen
Fehlende Textboxen bei Mülleimer im Haus oben rechts.
Fehlende Textboxen bei Mülleimer im Haus oben links.

**Reproduzieren**
*Schritte, um den Bug auszulösen*
Regale ansprechen im Pokecenter (Sylviria City)
Mülleimer im Haus in Sylviria City oben rechts  ansprechen.
Mülleimer im Haus in Sylviria City oben links im Untergeschoss ansprechen.

**Erwartetes Verhalten**
Es sollte eine Textbox erscheinen wie bei den unteren beiden Regalen
Es sollte eine Textbox erscheinen wie bei den anderen Mülleimern.
Es sollte eine Textbox erscheinen wie bei den anderen Mülleimern.
**Screenshots**
![Textboxen](https://user-images.githubusercontent.com/65260349/132871093-f124f7ae-283b-41d0-9e9e-72a80880ef7c.PNG)
![Text Müll](https://user-images.githubusercontent.com/65260349/132873338-051d1300-69a1-4423-96cb-094f4f534db4.PNG)
![TextMüll2](https://user-images.githubusercontent.com/65260349/132879920-25e268b3-ee8c-4fa4-81c9-5ab7098dd14f.PNG)

**Verwendeter Emulator / Hardware**
vba-m 2.1.4

**Comment by Dragonflysots** [comment]
Nachdem man das Item gefunden hat, ist dann da einfach nichts mehr. :D
