### ISSUE TITLE
NPCs with identical dialogue in Carun Center

### ISSUE THREAD

**Issue by Bassoonian** [pokemon-sots/pokemon-sots-issues#232]
**Describe the Bug**
Almost all NPCs (not the hiker) have identical dialogue in Carun Poké Center.

**Screenshots**
*If applicable, screenshots that show the bug.*
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/132886380-f809af3c-cf60-4bb6-b988-11c0b1516c66.png">
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/132886403-9d2555f8-ca8a-445c-880e-ab1ab47eff9b.png">
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/132886451-995250da-42cc-45b5-918d-a39ad0a94758.png">
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/132886473-ea13f611-3b81-4acd-86b4-a85b47450f05.png">

**Comment by Bassoonian** [comment]
Similarly, when the rival takes you into the Poké Center, the dialogue regarding the map occurs twice before the rival walks off.

**Comment by SBird1337** [comment]
english equivalent of #174

**Comment by Dragonflysots** [comment]
fixed
