### ISSUE TITLE
Unvollständiger Satz von Schwester Joy

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#24]
**Beschreibe den Bug**
Mitten im Satz von Schwester Joy ist das Gespräch beendet.

**Reproduzieren**
1. Gehe nach Carun City.
2. Laufe zum Pokemon Center und sprich Schwester Joy an.
3. Mitten im Satz ist das Gespräch beendet.

**Erwartetes Verhalten**
Vollständige Sätze.

**Screenshots**
![Unvollständiger Satz](https://user-images.githubusercontent.com/65140155/81518790-7dbd4480-933f-11ea-8c06-404c0920cb67.JPG)

**Verwendeter Emulator / Hardware**
mGBA ver. 0.8.1

**Zusätzliche Information**
Bevor ich irgend etwas Spiel relevantes gemacht habe bin ich zu Schwester Joy gelaufen (als sie vor dem Pokemon Center steht).

**Comment by SBird1337** [comment]
duplicate of #2
