### ISSUE TITLE
Rechtschreibfehler im Anfangsdialog mit Evelyn nachdem sie sich bedankt

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#248]
**Beschreibe den Bug**
Im Dialog von Evelyn steht "verhindert" jedoch sollte hier "verhindern" stehen.

**Reproduzieren**
1. Betrete Kalden
2. Triggere die Cutscene und im Anschluss das Gespräch mit Evelyn

**Erwartetes Verhalten**
Korrekte Rechtschreibung

**Screenshots**
![Rechtschreibfehler 12](https://user-images.githubusercontent.com/65140155/132916417-0f1f460f-3bf7-46d3-89f7-21519e1a82a1.jpg)

**Verwendeter Emulator / Hardware**
mGBA 0.9.2

**Comment by SBird1337** [comment]
fixed internally
