### ISSUE TITLE
Rechtschreibung Sammelthread

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#250]
**Beschreibe den Bug**
Im Dialog von Emma, nachdem Evelyn uns in Kalden in Gruppen unterteilt hat steht "auf deM Weg", sollte aber "auf deN Weg" heißen.

**Reproduzieren**
1. Betrete Kalden und triggere die Cutscene und anschließend die Dialoge
2. Im Dialog von Emma ist das Wort "dem" falsch

**Erwartetes Verhalten**
Korrekte Rechtschreibung

**Screenshots**
![Rechtschreibfehler 13](https://user-images.githubusercontent.com/65140155/132917282-c40073b9-8837-47ba-a55b-d53774c0463a.jpg)

**Verwendeter Emulator / Hardware**
mGBA 0.9.2

**Comment by xLiviusx** [comment]
Hier wird "zusammenhabe" zusammen geschrieben, was falsch ist.

![Grammatik 6](https://user-images.githubusercontent.com/65140155/132918135-c66d8d10-a342-4259-927f-e9135136b413.jpg)

**Comment by xLiviusx** [comment]
Ort: Kalden Pokecenter
Im Dialog der blonde Wanderin oben rechts - hier steht "vorrausichtlich" was falsch geschrieben ist. Richtig wird es "voraussichtlich" geschrieben.
![Rechtschreibfehler 14](https://user-images.githubusercontent.com/65140155/132918518-9f487dd6-ea61-43e3-a661-96fc1c57f98f.jpg)

**Comment by xLiviusx** [comment]
Ort: Kalden oben rechts im großem Haus im 1. OG.
![Grammatik 7](https://user-images.githubusercontent.com/65140155/132920265-9214de92-7615-4f66-a78a-4875060fb7e5.jpg)

**Comment by xLiviusx** [comment]
Ort: Kaldenweg Beim pflanzen einer Beere

![Rechtschreibfehler 15](https://user-images.githubusercontent.com/65140155/132920740-bcd2c60d-96ca-4b39-8bc8-1b7372d9c40e.jpg)

**Comment by SBird1337** [comment]
fixed internally
