### ISSUE TITLE
Englischer Text im Doppelkampf Reberapfad

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#254]
**Beschreibe den Bug**
Im Doppelkampf auf dem Reberapfad mit Juliet und John

**Reproduzieren**
1. Laufe im Reberapfad zu dem Doppelkampf
2. Starte den Doppelkampf
3. Am Anfang des Kampfes und Ende tauchen englische Begriffe auf

**Erwartetes Verhalten**
Einheitliche Sprache

**Screenshots**
![Übersetzung 2](https://user-images.githubusercontent.com/65140155/132923607-aa725e93-26f4-4162-8526-26747e4a2a35.jpg)

**Verwendeter Emulator / Hardware**
mGBA 0.9.2

**Comment by SBird1337** [comment]
It also says backpacker :D

**Comment by SBird1337** [comment]
fixed internally
