### ISSUE TITLE
Rechtschreibung/Grammatik Sammelthread

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#260]
**Beschreibe den Bug**
Im Dialog des Farmers (siehe Bild) wurde "gar nicht" zusammen geschrieben.

**Reproduzieren**
1. Betrete Grenar
2. Rede mit dem Farmer wie auf dem Bild zu sehen

**Erwartetes Verhalten**
Korrekte Rechtschreibung/Grammatik

**Screenshots**
![Grammatik 8](https://user-images.githubusercontent.com/65140155/132951215-dced99ed-6491-48ca-b566-af9420924a30.jpg)

**Verwendeter Emulator / Hardware**
mGBA 0.9.2

**Comment by xLiviusx** [comment]
Ort: Grenar (Im Haus über dem Farmer vom Bild weiter oben)

![Grammatik 9](https://user-images.githubusercontent.com/65140155/132951259-792258b2-43ad-410d-852f-4ae47355cb8c.jpg)

**Comment by xLiviusx** [comment]
Ort: Grenar (rechts von dem Haus der vorherigen Meldungen)
Das Wort "besten" wurde hier groß geschrieben, was falsch ist.

![Rechtschreibfehler 16](https://user-images.githubusercontent.com/65140155/132951592-dea02c97-5acb-4ced-9b17-296a6f532aee.jpg)

**Comment by xLiviusx** [comment]
Ort: Grenar (Blonder Junge links vom PokeCenter)
Ich denke, hier wurde das Wort "alles" zwischen "das" und "alleine" vergessen.

![Grammatik 10](https://user-images.githubusercontent.com/65140155/132952206-aecfe461-7360-47d7-8127-6a1d120587bd.jpg)

**Comment by xLiviusx** [comment]
Hier wurde bei der Beschreibung der Attacke Feuerfunken das "f" in der Mitte vergessen.

![Rechtschreibfehler 17](https://user-images.githubusercontent.com/65140155/132952944-97199845-e47f-442c-a5c4-96de5cbac62b.jpg)

**Comment by xLiviusx** [comment]
Ort: Felder von Grenar (im Kamp mit dem Reiter)
Hier wurde bei dem Wort "Nicht" der letzte Buchstabe vergessen.

![Rechtschreibfehler 18](https://user-images.githubusercontent.com/65140155/132953082-dd7a32bb-e7a7-411b-8d65-18a066f5dad4.jpg)

**Comment by xLiviusx** [comment]
Ort: Felder von Grenar/Grenarweg
Hier ist in der Einblendung der Route der Namen von der Route Grenarweg ein "w" zu viel.

![Rechtschreibfehler 19](https://user-images.githubusercontent.com/65140155/132953505-d383e7fe-59ac-4178-8460-75322cb4c52c.jpg)

**Comment by xLiviusx** [comment]
Ort: Grenarweg (2. Trainer)
Hier wurde das "r" bei "Würdest" vergessen.

![Rechtschreibfehler 20](https://user-images.githubusercontent.com/65140155/132953720-81995dbf-3ecd-4aa4-87fd-2d4516df8e07.jpg)

**Comment by xLiviusx** [comment]
Ort: Altera Gebirge (Ninjajunge)
Hier wurde im Dialog mit dem Ninjajungen das Wort "durchschaut" drei mal falsch geschrieben. (Alle drei Bilder sind vom selben Ninjajungen.

![Rechtschreibfehler 21](https://user-images.githubusercontent.com/65140155/132961414-795cf8e2-c5fb-493e-aa23-c8d99b528458.jpg)
![Rechtschreibfehler 22](https://user-images.githubusercontent.com/65140155/132961415-6c488ddd-07c5-4619-b751-589c6703a7e5.jpg)
![Rechtschreibfehler 23](https://user-images.githubusercontent.com/65140155/132961417-bb1b686f-be76-4f06-9fcb-1f2c434b0b5f.jpg)

**Comment by xLiviusx** [comment]
Ort: Im Kampf
Wenn ein Pokemon das Item Überreste trägt und das Pokemon am Ende der Runde geheilt wird, steht da, dass die Statuswerte geheilt werden, was nicht stimmt da die KP geheilt werden.

![Grammatik 12](https://user-images.githubusercontent.com/65140155/132961456-21e8cf32-5af2-41d8-bbba-c6cdbee3dac4.jpg)

**Comment by SBird1337** [comment]
fixed internally
