### ISSUE TITLE
Layerfehler von Tauros in Grenar

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#263]
**Beschreibe den Bug**
Beim betreten des Hauses rechts von Grenar war der halbe Kopf von Tauros im Trinkbecken.

**Reproduzieren**
1. Gehe nach Grenar
2. Betrete das Haus rechts von Grenar

**Erwartetes Verhalten**
Vollständig sichtbare Pokemon 

**Screenshots**
![Layer 3](https://user-images.githubusercontent.com/65140155/132951955-ff74fe6c-1ff3-4ea1-bb1d-95c70bf70ec0.jpg)

**Verwendeter Emulator / Hardware**
mGBA 0.9.2

**Comment by xLiviusx** [comment]
Ort: Grenar (rechtes Haus)
Wie im Report von #261 mit dem Layerfehler von Miltank und Tauros.

![Layer 4](https://user-images.githubusercontent.com/65140155/132952035-fe5626fe-a5d6-4675-8107-a94bcd389726.jpg)

**Comment by xLiviusx** [comment]
Ort: Grenar (linkes Haus vom PokeCenter)
Selber Layerfehler wie oben mit der gleichen Ausführung.

![Layer 5](https://user-images.githubusercontent.com/65140155/132952360-3dfaa6fe-917d-41ec-9eb0-d8d0a26bb32a.jpg)

**Comment by xLiviusx** [comment]
Ort: Grenar (links von der Windmühle)
Der kleine Stein ist begehbar.

![Layer 6](https://user-images.githubusercontent.com/65140155/132952803-d59fd3bb-f91c-46b2-8208-5107c2af9493.jpg)

**Comment by xLiviusx** [comment]
Ort: Felder von Grenar (oben bei den Heuballen)
Links von dem grünen Tor kann man in den Heuballen hinein laufen.

![Layer 7](https://user-images.githubusercontent.com/65140155/132953211-ee819d73-00d9-4672-8c53-0d58d76b211a.jpg)

**Comment by Dragonflysots** [comment]
fix
