### ISSUE TITLE
Npc dreht sich nicht zu einem beim ansprechen

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#264]
**Beschreibe den Bug**
Der Npc auf dem Bild dreht sich nicht um, wenn man ihn anspricht.

**Reproduzieren**
1. Gehe nach Grenar
2. Laufe hoch zu den Bienenstöcken und Markständen
3. Sprich den Npc an der oben links neben einem Miltank steht

**Erwartetes Verhalten**
Einheitliche Animationen beim ansprechen von Npcs

**Screenshots**
![Bug 9](https://user-images.githubusercontent.com/65140155/132952581-6536e40b-32cf-4ce3-b886-85e3d702a745.jpg)

**Verwendeter Emulator / Hardware**
mGBA 0.9.2

**Comment by Dragonflysots** [comment]
fix
