### ISSUE TITLE
Großer Layerfehler bei Felder von Grenar

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#266]
**Beschreibe den Bug**
In den Feldern von Grenar kann man unterhalb der Laterne außerhalb des eigentlichen Geländes umher laufen.

**Reproduzieren**
1. Gehe nach Felder von Grenar
2. Laufe so lange nach rechts, bis der zweite Reiter erscheint.
3. Laufe anschließend nach unten bis zur markierten Stelle im Screen

**Erwartetes Verhalten**
Kein begehen nicht geeigneter Gebiete

**Screenshots**
![Layer 8](https://user-images.githubusercontent.com/65140155/132953392-90e0f22f-cec0-4a86-8771-29c940e5790d.jpg)

**Verwendeter Emulator / Hardware**
mGBA 0.9.2

**Comment by xLiviusx** [comment]
Direkt darunter kann man nicht bis zu der Wand laufen sondern wird von etwas blockiert.

![Layer 9](https://user-images.githubusercontent.com/65140155/132953457-4ec4b16d-295a-4243-8afe-ab00a540a59e.jpg)

**Comment by Dragonflysots** [comment]
fix
