### ISSUE TITLE
Englischer Text am Schild am Eingang des Grenarwegs

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#267]
**Beschreibe den Bug**
Der Text beim ansprechen des Schilds ist auf englisch.

**Reproduzieren**
1. Betrete den Grenarweg
2. Rede mit dem Schild am Grenarweg Eingang

**Erwartetes Verhalten**
Einheitliche Sprache

**Screenshots**
![Übersetzung 3](https://user-images.githubusercontent.com/65140155/132953547-6c01555e-4e17-4d70-847d-8f14869556d2.jpg)

**Verwendeter Emulator / Hardware**
mGBA 0.9.2

**Comment by Dragonflysots** [comment]
fix
