### ISSUE TITLE
Merkwürdige Bewegung des Protagonisten wenn man gegen den Baum läuft/rennt

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#268]
**Beschreibe den Bug**
Rennt man gegen den rechten Baum auf der rechten Seite des Baumes, so läuft man automatisch diagonal.

**Reproduzieren**
1. Gehe nach Grenarweg
2. Laufe bis kurz vor Bergpasshöhle
3. Laufe gegen den im Screen markierten Baum

**Erwartetes Verhalten**
Einheitliches Kollisionsverhalten

**Screenshots**
![Bug 11](https://user-images.githubusercontent.com/65140155/132953883-993c8d44-c2d1-43fc-b995-b0ac9e0fdb8d.jpg)

**Verwendeter Emulator / Hardware**
mGBA 0.9.2

**Zusätzliche Information**
Auch wenn das vielleicht ein Bug ist, sieht es verdammt gut aus und war etwas überrascht da es sich sehr smooth anfühlt. :D

**Comment by Dragonflysots** [comment]
fix
