### ISSUE TITLE
Englischer Text beim Tauschen von Pokemon

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#269]
**Beschreibe den Bug**
Während des Tauschens ist der Text auf englisch.

**Reproduzieren**
1. Gehe nach Grenar
2. Sprich im Pokecenter mit dem Farmer oben links
2. Tausche ein Voltilamm gegen Frubberl

**Erwartetes Verhalten**
Einheitliche Sprache

**Screenshots**
![Übersetzung 4](https://user-images.githubusercontent.com/65140155/132954140-dcdd135a-1a53-4661-9a29-28491659be8e.jpg)

**Verwendeter Emulator / Hardware**
mGBA 0.9.2

**Comment by SBird1337** [comment]
I think this is fixed already
