### ISSUE TITLE
Rechtschreibfehler nach dem 1. Kampf gegen Emma

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#27]
**Beschreibe den Bug**
Nach dem ersten Kampf gegen Emma empfiehlt sie uns, ein Pokemon Center aufzusuchen. Jedoch ist das Wort "aufsuchen" hier mit zwei "s" geschrieben. Ebenso ist hier das Wort "sicher" falsch geschrieben worden. Stattdessen wurde "sich" geschrieben.

**Reproduzieren**
1. Kämpfe gegen Emma (1. Kampf).
2. Nach dem Kampf erscheint automatisch die Textbox mit beiden Rechtschreibfehlern.

**Erwartetes Verhalten**
Korrekte Rechtschreibung.

**Screenshots**
![Rechtschreibfehler10](https://user-images.githubusercontent.com/65140155/81521192-c2001300-9346-11ea-9c23-00e67b5d85a9.JPG)
![Rechtschreibfehler11](https://user-images.githubusercontent.com/65140155/81521199-c4fb0380-9346-11ea-8416-5676901d3464.JPG)

**Verwendeter Emulator / Hardware**
mGBA ver. 0.8.1

**Zusätzliche Information**
n/a

**Comment by SBird1337** [comment]
superseded by a minor rewrite of the prologue
