### ISSUE TITLE
Color Game House: 2 people on ground floor have the same dialogue

### ISSUE THREAD

**Issue by SBird1337** [pokemon-sots/pokemon-sots-issues#270]
**Describe the Bug**
Title

**Reproduce**
Title (Color game house Lairaku top left)

**Expected Behavior**
Different Dialogues

**Screenshots**
/

**Used Emulator / Hardware**
does not matter

**Misc. Information**
/

**Comment by Dragonflysots** [comment]
konnte nicht reproduziert werden
