### ISSUE TITLE
[Critical] Umbrella Lady will break the game by advancing a story variable

### ISSUE THREAD

**Issue by SBird1337** [pokemon-sots/pokemon-sots-issues#275]
**Describe the Bug**
Talking to an umbrella lady in montera will set an internal variable that will break quest progress and thus game progress in Montera. If you encounter her, don't talk to her!

**Reproduce**
*Steps to reproduce*
1. Go to `Montera`
2. Talk to the NPC seen in the screenshot
3. You cannot complete the quest `On the Rocks` (`Bergeshöhen` in german) because the parasol ladies in the house won't fight against you.

**Expected Behavior**
No story advancement by talking to the NPC

**Screenshots**
![image](https://user-images.githubusercontent.com/3799173/132966423-20214740-35d9-4f37-85ee-8fbad1fa0638.png)

**Used Emulator / Hardware**
mGBA

**Misc. Information**

**Comment by Dragonflysots** [comment]
fixed in the next release
