### ISSUE TITLE
Grafikfehler Mühle

### ISSUE THREAD

**Issue by xydragonxy** [pokemon-sots/pokemon-sots-issues#276]
**Beschreibe den Bug**
Ein Grafikfehler an der Mühle 

**Reproduzieren**
STelle dich an der mühle ganz nach rechts und der Grafikfehler taucht auf

**Erwartetes Verhalten**
Sollte nicht vorhanden sein

**Screenshots**
![Grafikfehler Mühle](https://user-images.githubusercontent.com/65260349/132984089-c505f1e4-32db-4d2d-be91-203e2e921db6.PNG)

**Verwendeter Emulator / Hardware**
vba-m 2.1.4

**Zusätzliche Information**
*Jegliche Information, die ansonsten noch nützlich sein könnte, um uns bei der Lösung des Problems zu helfen.*

**Comment by SBird1337** [comment]
probably an emulator issue

**Comment by SBird1337** [comment]
not an emulator issues, we're running out of OAM duty cycles, fixed internally
