### ISSUE TITLE
Nicht begehbares Feld Araji Katakomben

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#277]
**Beschreibe den Bug**
Wie im Screen zusehen ist der markierte Bereich nicht begehbar

**Reproduzieren**
1. Betrete Araji Katakomben
2. Triggere die Sequenz mit Lenny und Tönfa
3.  Laufe zu der Position wie im Screen gezeigt

**Erwartetes Verhalten**
Keine unsichtbaren Blöcke

**Screenshots**
![Bug 13](https://user-images.githubusercontent.com/65140155/132984486-5c7b4eb5-2e45-4a3f-8e4a-627b119f9ff5.jpg)

**Verwendeter Emulator / Hardware**
mGBA 0.9.2

**Comment by Dragonflysots** [comment]
fix
