### ISSUE TITLE
Layerfehler Grenar

### ISSUE THREAD

**Issue by xydragonxy** [pokemon-sots/pokemon-sots-issues#278]
**Beschreibe den Bug**
An der Gezeigten stelle tritt ein Layerfehler auf

**Reproduzieren**
*Schritte, um den Bug auszulösen*
An dem Haus oben Rechts in Grenar an der der Gezeigten stelle stehen und warten bis der Npc an seiner gezeigten Position ist. 

**Screenshots**
![Layerfehler Npc](https://user-images.githubusercontent.com/65260349/132984994-10e41a09-96c4-47ac-9c35-06a2c31c60fa.PNG)
![Layerfehler Npc2](https://user-images.githubusercontent.com/65260349/132985073-f5b3b1d0-b0ca-4d5b-b454-83daa6e1c0e3.PNG)

**Verwendeter Emulator / Hardware**
vba-m 2.1.4

**Zusätzliche Information**
*Jegliche Information, die ansonsten noch nützlich sein könnte, um uns bei der Lösung des Problems zu helfen.*

**Comment by Dragonflysots** [comment]
fix
