### ISSUE TITLE
Layerfehler Araji Katakomben

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#279]
**Beschreibe den Bug**
Nach dem 2. Rätsel, nachdem sich die Tür öffnet muss man die Leiter hoch. Auf der rechten Seite kann man in die Wand laufen.

**Reproduzieren**
1. Betrete Araji Katakomben, beende das 2. Rätsel
2. Laufe durch die geöffnete Tür, klettere die Leiter nach oben
3. Wie im Screen zu sehen, kann man hier in die Wand laufen

**Erwartetes Verhalten**
Keine begehbaren Wände

**Screenshots**
![Layer 10](https://user-images.githubusercontent.com/65140155/132985342-671100ac-b6ee-4e90-a711-401c404f6bd3.jpg)

**Verwendeter Emulator / Hardware**
mGBA 0.9.2

**Comment by xLiviusx** [comment]
Ort: Araji Katakomben (unterhalb des Raumes mit den vielen Statuen)
Hier sieht man die Haarspitzen durch die Wand, die man eigentlich nicht sehen sollte.

![Layer 11](https://user-images.githubusercontent.com/65140155/132985471-c90df43e-63af-40c4-8bfe-bafeb54e2198.jpg)

**Comment by xLiviusx** [comment]
Ort: Araji Katakomben (gleicher Raum wie im Bild ein weiter oben)
Bei der markierten Fläche kann man die Haarspitzen durch die Wand sehen, gegenüber wiederum nicht.

![Layer 12](https://user-images.githubusercontent.com/65140155/132985532-c256ae4b-98ef-4c52-ba05-48da3f5daadc.jpg)

**Comment by xLiviusx** [comment]
Ort: Araji Katakomben (Im Raum nachdem man die drei Statuen auf die richtige Position gebracht hat)
Wie im Screen zu sehen, sind die markierten Flächen nicht begehbar.

![Bug 15](https://user-images.githubusercontent.com/65140155/132986108-445162f7-e047-4547-bdcb-1c98ec281f3d.jpg)

**Comment by xLiviusx** [comment]
Ort: Araji Katakomben (siehe Screen des Rätsels)
Bei den weißen Säulen kann man, je nach dem ob man von oben oder unten auf die linke/rechte Seite zu läuft , die Haare sehen bzw. nicht sehen.

1. Screen von oben
![Layer 13-1](https://user-images.githubusercontent.com/65140155/132987277-1625d1d7-8de4-47ed-a07b-241c1aefb07f.jpg)

2. Screen von unten
![Layer 13-2](https://user-images.githubusercontent.com/65140155/132987286-34d52453-2ce1-45ee-8634-4ae234cc21dc.jpg)

**Comment by Dragonflysots** [comment]
fix
