### ISSUE TITLE
Layer, Kollisionsfehler und Textboxen in Lairaku

### ISSUE THREAD

**Issue by xydragonxy** [pokemon-sots/pokemon-sots-issues#280]
*Bitte fülle dieses Template aus, und lösche vor dem Abschicken die Platzhalter, sowie diese Zeile.*

**Beschreibe den Bug**
Ein SammelIssue zu Lairaku 
1.Screen Haus Links oben
2. Haus Rechts oben
3. Haus Rechts oben Textbox
4. Pokecenter
5. Pokecenter unten
6. Pokecenter Links daneben Layerfehler und Out of Map fehler
7. Lampe unter Pension Kollision
8. Unter der Pension Kollision

**Screenshots**
![Lairaku HausOL Textboxen](https://user-images.githubusercontent.com/65260349/132987950-005c9778-f2b6-468d-9ea2-75d895346820.PNG)
![Lairaku HausOR Layerfehler](https://user-images.githubusercontent.com/65260349/132987958-5af6a2b1-4a0b-46db-a694-2a5b819da96c.PNG)
![Lairaku HausOR Textbox](https://user-images.githubusercontent.com/65260349/132987976-e0761afd-d996-478d-a3cc-2fc2761972e1.PNG)
![Lairaku1 Kollisionsfehler](https://user-images.githubusercontent.com/65260349/132987991-e3310e89-4430-4d4c-a24e-74494a70883d.PNG)
![Lairaku1 Kollisionsfehler2](https://user-images.githubusercontent.com/65260349/132988008-28aa510e-7a6f-41be-9aeb-c3d5a82bed9f.PNG)
![Lairaku3 Layerfehler](https://user-images.githubusercontent.com/65260349/132988022-8a5fbf6a-bdd2-4aa7-bcba-f0539f24e8b2.PNG)
![Lairaku4 Kollisionsfehler3](https://user-images.githubusercontent.com/65260349/132988050-cb1eba71-fca4-4cbd-a538-f7f47bc39532.PNG)
![Lairaku5 Kollesionfehler3](https://user-images.githubusercontent.com/65260349/132988066-19c6b3dd-4b7d-4e56-9368-9612c2df29a0.PNG)

**Verwendeter Emulator / Hardware**
vba-m 2.1.4

**Zusätzliche Information**
*Jegliche Information, die ansonsten noch nützlich sein könnte, um uns bei der Lösung des Problems zu helfen.*

**Comment by Dragonflysots** [comment]
fix
