### ISSUE TITLE
Englischer text

### ISSUE THREAD

**Issue by 4Reddy** [pokemon-sots/pokemon-sots-issues#281]
**Beschreibe den Bug**
*Englisch Text im Trainer Kampf.*

**Reproduzieren**
*Schritte, um den Bug auszulösen*
1. Gehe nach Reberapfad
2. Beginne einen kampd mit dem im Bild zu sehenden NPC

**Screenshots**
*![Screenshot_2021-09-12-21-58-19-664_com.fastemulator.gba.jpg](https://user-images.githubusercontent.com/65133519/133001097-ed348a09-693e-4058-b232-d23b26a6cfef.jpg)*

**Comment by SBird1337** [comment]
should be fixed already
