### ISSUE TITLE
Frau spricht von ihrer frau

### ISSUE THREAD

**Issue by xydragonxy** [pokemon-sots/pokemon-sots-issues#287]
**Beschreibe den Bug**
Frau spricht von ihrer frau

**Reproduzieren**
*Schritte, um den Bug auszulösen*
Mizera City Links das Hochhaus neben dem Pokecenter.
Oberste Etage mit der Frau sprechen

**Erwartetes Verhalten**
Soll die Frau ne Frau haben oder ein Mann im Text.

**Screenshots**
![Frau frau](https://user-images.githubusercontent.com/65260349/133003054-c02e96b0-7b88-4b35-9586-37b61cfa14be.PNG)

**Verwendeter Emulator / Hardware**
vba-m 2.1.4

**Comment by Dragonflysots** [comment]
fix
