### ISSUE TITLE
KRITISCH: Mizeria City Markt Vogelfänger bringt Spiel zum Absturz

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#288]
**Beschreibe den Bug**
Sprich mit dem Vogelfänger links der Verkäuferin auf der 3. Etage.

**Reproduzieren**
1. Gehe nach Mizeria City
2. Rede mit dem auf dem Bild zu sehenden NPC
3. Teleport Geräusche zu hören + Spiel Absturz

**Erwartetes Verhalten**
Keine Dialoge die zum Spielcrash führen

**Screenshots**
![Bug 19](https://user-images.githubusercontent.com/65140155/133003282-5d62ad29-6704-47f1-97fc-78a383d8a912.jpg)

**Verwendeter Emulator / Hardware**
mGBA 0.9.2

**Comment by Dragonflysots** [comment]
#fixed in the next release
