### ISSUE TITLE
Nachtnebel trifft Kampf Pokemon?!

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#289]
**Beschreibe den Bug**
Bei mir hat eben im Kampf die Attacke Nachtnebel (Schaden abhängig vom Level des Anwenders) ein Kampf-Pokemon getroffen, was eigentlich nicht der Fall sein sollte. 

**Reproduzieren**
1. Setze Nachtnebel gegen ein Kampf-Pokemon ein

**Erwartetes Verhalten**
Geist Attacken sollten keine Normal/Kampf Pokemon treffen dürfen.

**Verwendeter Emulator / Hardware**
mGBA 0.9.2

**Comment by Dragonflysots** [comment]
Geist Attacken treffen Kampf Pokémon.

![image](https://user-images.githubusercontent.com/27623565/133056666-abbe7a0e-2be5-4764-b055-a549f9dc0286.png)
