### ISSUE TITLE
Rechtschreibung/Grammatik Sammelthread

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#290]
**Beschreibe den Bug**
Das Wort "erreichenbar" gibt es so nicht. Sollte wohl "erreichbar" heißen.

**Reproduzieren**
1. Beende die Araji Katakomben
2. Triggere das Gespräch mit Meister Tönfa

**Erwartetes Verhalten**
Korrekte Rechtschreibung/Grammatik

**Screenshots**
![Rechtschreibfehler 24](https://user-images.githubusercontent.com/65140155/133005423-83499252-766d-4716-8bae-5a62ca22f7e6.jpg)

**Verwendeter Emulator / Hardware**
mGBA 0.9.2

**Comment by xLiviusx** [comment]
Ort: Montera 
Triggere das Gespräch mit Lenny nachdem du die Araji Katakomben beendet hast.
Hier ist das Wort "Voraussetzungen" mit zwei "r" geschrieben.

![Rechtschreibfehler 25](https://user-images.githubusercontent.com/65140155/133005465-5c9bcdf5-e49c-4025-b684-37c5db5e0f8d.jpg)

**Comment by xLiviusx** [comment]
Ort: Route, links von Grenar (dort wo der Affengaukler war den Weg versperrt hat)
"weiterwandern" wird nicht zusammen geschrieben.

![Rechtschreibfehler 26](https://user-images.githubusercontent.com/65140155/133005494-d48aba28-5f9d-4bfc-942c-be4d1012d2e8.jpg)

**Comment by xLiviusx** [comment]
Ort: Mizeria City (Haus leider vergessen)
Hier wurde das Pokemon "Felilou" falsch geschrieben.

![Rechtschreibfehler 27](https://user-images.githubusercontent.com/65140155/133005527-f63c1af1-0345-4982-9c49-68addcc368f3.jpg)

**Comment by xLiviusx** [comment]
Ort: Mizeria City (Pokecenter)
Hier wurde das "g" in "Bergpfad" vergessen.

![Rechtschreibfehler 28](https://user-images.githubusercontent.com/65140155/133005550-b4824db0-2d2b-4c2d-897b-0860247aa06a.jpg)

**Comment by xLiviusx** [comment]
Ort: Mizeria City (links von Hüterin Evelyn)
Hier ist das "s" zu viel.

![Rechtschreibfehler 29](https://user-images.githubusercontent.com/65140155/133005581-b5fb164c-4c0a-4e30-8ab9-0dd9de74170d.jpg)

**Comment by xLiviusx** [comment]
Ort: Mizeria City (blonder Junge)
"Wahnsinn" wird hier groß geschrieben.

![Rechtschreibfehler 30](https://user-images.githubusercontent.com/65140155/133005596-4cd7c2f6-bb3a-4285-824d-d087c220829f.jpg)

**Comment by xLiviusx** [comment]
Ort: Mizeria City (oberhalb des Pokecenters)
Es heißt mit "den" Motorrädern.

![Rechtschreibfehler 31](https://user-images.githubusercontent.com/65140155/133005609-a40298f2-d098-4b67-9542-f76b913d0cf3.jpg)

**Comment by xLiviusx** [comment]
Ort: Mizeria City (die alte Dame links oben von der Stadt)
Das Wort "besten" wurde hier groß geschrieben.

![Rechtschreibfehler 32](https://user-images.githubusercontent.com/65140155/133005630-c0faab10-7e50-4e80-a287-ec1d9646a8cd.jpg)

**Comment by xLiviusx** [comment]
Ort: Mizeria City (Polizeiwache 1. OG)
Das Wort "Patrouille" wurde hier falsch geschrieben.

![Rechtschreibfehler 33](https://user-images.githubusercontent.com/65140155/133005645-64a5e95b-53b5-458d-9a98-a32619fd80cb.jpg)

**Comment by xLiviusx** [comment]
Ort: Mizeria City (Kneipe)
"Neinnein" sollte hier auseinander geschrieben sein.

![Rechtschreibfehler 34](https://user-images.githubusercontent.com/65140155/133005660-fcdabddb-8588-4a03-97d0-cbb352e261a8.jpg)

**Comment by xLiviusx** [comment]
Ort: Mizeria City (Haus vergessen)
"farbenfroh" wird hier klein geschrieben.

![Rechtschreibfehler 35](https://user-images.githubusercontent.com/65140155/133005676-7bf52901-1221-4a00-85f1-a84b4acd826a.jpg)

**Comment by xLiviusx** [comment]
Ort: Mizeria City (Polizeiwache nach Banditen Quest)
Hier hat man das "n" mit einem "m" vertauscht.

![Rechtschreibfehler 36](https://user-images.githubusercontent.com/65140155/133005690-bff045cc-202d-42e4-a2d3-5232bc4fec4b.jpg)

**Comment by xLiviusx** [comment]
Ort: Mizeria City (Bank, während des Überfalls)
Hier ist der Buchstabe "t" zu viel.

![Rechtschreibfehler 37](https://user-images.githubusercontent.com/65140155/133005717-641d383f-8713-4e45-b54d-f55ecddfb0db.jpg)

**Comment by xLiviusx** [comment]
Ort: Mizeria City (Leuchtturm)
Hier hat man das "t" in Heiligtum vergessen.

![Rechtschreibfehler 38](https://user-images.githubusercontent.com/65140155/133005730-a932d030-b53d-45ab-8bf5-065505de6d69.jpg)

**Comment by xLiviusx** [comment]
Ort: Montera (nach dem Kampf mit dem Hüter)
Hier fehlt das Wort "du".

![Grammatik 14](https://user-images.githubusercontent.com/65140155/133005775-1391aa2b-d061-443b-964f-c90ef775214e.jpg)

**Comment by xLiviusx** [comment]
Ort; Grenar (glaube neben einem Höhlenausgang)
"gar kein" wird nicht zusammen geschrieben.

![Grammatik 15](https://user-images.githubusercontent.com/65140155/133005816-0e4d35cc-04dc-4255-88cc-e0df51e27d47.jpg)

**Comment by xLiviusx** [comment]
Ort: Iyasu City
Das Wort "kann" ist hier fehl am Platze.

![Grammatik 16](https://user-images.githubusercontent.com/65140155/133005845-74b70eb7-32e3-4aa6-8d4a-8b64dd0189b4.jpg)

**Comment by xLiviusx** [comment]
Ort: Mizeria City (Haus vergessen)
Hier hat man das Komma vergessen.

![Grammatik 17](https://user-images.githubusercontent.com/65140155/133005865-07a867ff-6524-47b1-892c-b65104a3fe6e.jpg)

**Comment by xLiviusx** [comment]
Ort: Logbuch (Nach erhalt der Talisman Quest)
"nette" wird kleingeschrieben und das "es" ist hier ebenfalls falsch. Da sollte ein "ihn" stehen.

![Grammatik 18](https://user-images.githubusercontent.com/65140155/133005908-5285e8d5-fb84-4a2d-b6f0-7b8ce827c62d.jpg)

**Comment by xLiviusx** [comment]
Ort: Durchgang nach Mizeria City
An dieser Stelle wird "genauso" zusammen geschrieben.

![Grammatik 19](https://user-images.githubusercontent.com/65140155/133005964-0f3728ea-9dca-401c-aa4d-b235d7b63bce.jpg)

**Comment by xLiviusx** [comment]
Ort: Mizeria City (Haus vergessen)
Hier fehlt ein Komma

![Grammatik 20](https://user-images.githubusercontent.com/65140155/133005979-578ceed7-fb00-4271-970e-89889962cf7a.jpg)

**Comment by xLiviusx** [comment]
Ort: Mizeria City (Einkaufszentrum)
Gar nicht wird gar nicht zusammen geschrieben. :p

![Grammatik 21](https://user-images.githubusercontent.com/65140155/133005996-1c4c9f02-eb2a-4dc9-8f44-a0f3d77e1cf5.jpg)

**Comment by xLiviusx** [comment]
Ort: Mizeria City (Einkaufszentrum (gleiche Etage wie ein Bild weiter oben)
Gar nicht wird immer noch nicht zusammen geschrieben. :p

![Grammatik 22](https://user-images.githubusercontent.com/65140155/133006022-ed8905b6-f916-4453-94c5-621f34b4c1bc.jpg)

**Comment by xLiviusx** [comment]
Ort: Mizeria City
Hier würde ich vorschlagen, zwischen den beiden Wörtern ein "mach" einzufügen.

![Grammatik 23](https://user-images.githubusercontent.com/65140155/133006048-ca8a09c7-2c40-4799-bf22-5713aafe7824.jpg)

**Comment by Dragonflysots** [comment]
fixed
