### ISSUE TITLE
Mizeria Kollision, Layerfehler, Grafikfehler

### ISSUE THREAD

**Issue by xydragonxy** [pokemon-sots/pokemon-sots-issues#291]
**Reproduzieren**
*Schritte, um den Bug auszulösen*
1.Mizeria Restaurant
2.Mizeria Einkaufszentrum 3 Etage
3.Mizeria unter der Bank
4.Mizeria in der Bank der rechte und linke Schalter Layerfehler
5.Mizeria Rockerbar 1 Etage beide Bäume von Links betreten
6.Mizeria Rockerbar EG Grafikfehler Flaschen und Kollisionsfehler
7.Mizeria Polizei 

**Screenshots**
![Mizera City Kollision1](https://user-images.githubusercontent.com/65260349/133005386-b6d60586-3c5e-4fdb-b96a-e70160e79ce4.PNG)
![Mizera City Kollision2](https://user-images.githubusercontent.com/65260349/133005397-52f0f273-98a1-4eb5-ba87-327df3cfb274.PNG)
![Mizeria KollisionsfehlerBank](https://user-images.githubusercontent.com/65260349/133005407-966ad95d-950a-42b7-b9c1-e544d047889a.PNG)
![Mizeria LayerfehlerBank](https://user-images.githubusercontent.com/65260349/133005419-af9e67b3-a5c8-43ae-9321-edbb7782fdab.PNG)
![Mizeria KollisionsfehlerBar](https://user-images.githubusercontent.com/65260349/133005434-c8a63f97-db39-49e3-8e51-c75aed6342d9.PNG)
![Mizeria KollisionundGrafikfehler](https://user-images.githubusercontent.com/65260349/133005469-58c015b4-aaf8-4f32-a150-d49a8318fd48.PNG)
![Mizeria KollisionsfehlerPolizei](https://user-images.githubusercontent.com/65260349/133005501-3a09fa09-706a-4357-8cdc-27ea401f6956.PNG)

**Verwendeter Emulator / Hardware**
vba-m 2.1.4

**Comment by xLiviusx** [comment]
Ort: Polizeiwache EG

![Layer 15](https://user-images.githubusercontent.com/65140155/133006506-cab374c4-3b28-4f0c-b932-02b58a9c0101.jpg)

**Comment by xLiviusx** [comment]
Ort: Polizeiwache 1. OG

![Layer 16](https://user-images.githubusercontent.com/65140155/133006525-b7dfe4f9-eb9a-43c1-ba85-4fd0d2fdeee6.jpg)

**Comment by xLiviusx** [comment]
Ort: Haus unbekannt

![Layer 17](https://user-images.githubusercontent.com/65140155/133006534-46a27b27-b501-4b0a-a7be-21e544bdd50b.jpg)

**Comment by Dragonflysots** [comment]
fixed
