### ISSUE TITLE
Ausschlüpfen 

### ISSUE THREAD

**Issue by xydragonxy** [pokemon-sots/pokemon-sots-issues#292]
**Beschreibe den Bug**
Text hat einen anderen Hintergrund, Text in Englisch 

**Reproduzieren**
Schlüpfe ein Ei aus

**Erwartetes Verhalten**
Text sollte Deutsch sein und Hintergrund der textbox sollte weiß sein.

**Screenshots**
![Ei](https://user-images.githubusercontent.com/65260349/133005657-55eae543-90d5-4252-a945-0858b4467d5d.PNG)

**Verwendeter Emulator / Hardware**
vba-m 2.1.4

**Comment by SBird1337** [comment]
fixed internally
