### ISSUE TITLE
Bewegungen des Npcs am Lairakupfad

### ISSUE THREAD

**Issue by xydragonxy** [pokemon-sots/pokemon-sots-issues#293]
**Beschreibe den Bug**
Bewegungen des Npcs (Lairakupfad) sehen Merkwürdig aus

**Reproduzieren**
Beobachte den Npcs im Bild er macht komische Laufbewegungen und Animationen

**Erwartetes Verhalten**
*Eine klare Beschreibung, wie das Verhalten an dieser Stelle sein sollte.*

**Screenshots**
![Npc Bewegungen Lairaku Pfad](https://user-images.githubusercontent.com/65260349/133005703-c25378f5-cdc8-4dc1-a53d-ada2ded8d79b.PNG)

**Verwendeter Emulator / Hardware**
*Welcher Emulator wurde verwendet, als der Bug auftrat?*

**Comment by Dragonflysots** [comment]
fix
