### ISSUE TITLE
Übersetzungen

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#294]
**Beschreibe den Bug**
Hier ist die englische Abkürzung für AP.

**Reproduzieren**
1. Öffne die Übersicht eines Pokemon
2. Wechsle zu dem Reiter "Attacken"

**Erwartetes Verhalten**
Einheitliche Sprache

**Screenshots**
![Übersetzung 5](https://user-images.githubusercontent.com/65140155/133006131-871b9ab5-8766-4127-b98f-e4a03fa27d8f.jpg)

**Verwendeter Emulator / Hardware**
mGBA 0.9.2

**Comment by xLiviusx** [comment]
Ort: Mizeria City (Bank)
Englischer Text von der Gerät.

![Übersetzung 6](https://user-images.githubusercontent.com/65140155/133006148-6cba541d-65f1-4e92-8f0c-32128e70ab54.jpg)

**Comment by xLiviusx** [comment]
Ort: Mizeria City (Kneipe)
Die Jukebox hat ebenfalls einen englischen Text.

![Übersetzung 7](https://user-images.githubusercontent.com/65140155/133006165-d9ae968e-8dcb-4253-8c63-8bb326905477.jpg)

**Comment by Dragonflysots** [comment]
@SBird1337 Die PP konnte ich nicht finden, der rest hat vorrübergehend einen Text.

**Comment by SBird1337** [comment]
fixed internally
