### ISSUE TITLE
Bugs in Mizeria City

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#295]
**Beschreibe den Bug**
Markierte Frau hat keinen Dialog.

**Reproduzieren**
1. Betrete Mizeria City
2. Rede mit dem auf dem Bild zu sehenden NPC

**Erwartetes Verhalten**
Npcs sollten ansprechbar sein wenn man neben ihnen steht.

**Screenshots**
![Bug 16](https://user-images.githubusercontent.com/65140155/133006231-f7be59b5-59c4-4c43-9a7d-c97333795d5d.jpg)

**Verwendeter Emulator / Hardware**
mGBA 0.9.2

**Comment by xLiviusx** [comment]
Ort: Mizeria City
Npc reden von einem Shnurgarst, unter ihm ist aber ein Charmian.

![Bug 17](https://user-images.githubusercontent.com/65140155/133006253-54fb0c07-a46f-45cd-b6be-b373d5abf6f6.jpg)

**Comment by xLiviusx** [comment]
Ort: Mizeria City (Einkaufszentrum)
Markierten Npcs haben kein Dialog.

![Bug 20](https://user-images.githubusercontent.com/65140155/133006292-5bad9e8b-b278-4953-ae85-22392bde7f85.jpg)

**Comment by xLiviusx** [comment]
Ort: Mizeria City (Haus vergessen)
Markierte Npc gibt dir ein Item welches du immer wieder bekommst bei erneutem ansprechen.

![Bug 21](https://user-images.githubusercontent.com/65140155/133006312-af845d90-4e57-4e24-903c-12c0b21f8205.jpg)

**Comment by xLiviusx** [comment]
Ort: Mizeria City
Markierte Npc lässt sich nur von vorne ansprechen.

![Bug 22](https://user-images.githubusercontent.com/65140155/133006325-1c2210a3-be83-4b37-907f-a99daaeb13d8.jpg)

**Comment by xLiviusx** [comment]
Ort: Mizeria City (Haus vergessen)
Markierte Npc gibt dir ein Finsterstein welches man bei erneutem ansprechen immer wieder bekommt.

![Bug 23](https://user-images.githubusercontent.com/65140155/133006363-085f7ca7-ed3f-47c9-a81e-aa797a9ba629.jpg)

**Comment by xLiviusx** [comment]
Ort: Mizeria City (Logbuch Eintrag nachdem man die Diebe in der Bank besiegt hat)
In der Bank ist die Rede davon, dass ein Dieb fliehen konnte, im Logbuch steht davon nichts sondern das scheinbar alle Diebe gefangen wurden.
Des weiteren wurde vor "Leuchtturm" das Wort "den" vergessen.

![Bug 24](https://user-images.githubusercontent.com/65140155/133006410-5bf6e0c6-ebb6-454f-a46a-78ccd93905cd.jpg)

**Comment by xLiviusx** [comment]
Ort: Mizeria City (Einkaufszentrum)
Alle Regale im EZ sind nicht ansprechbar.

![Bug 18](https://user-images.githubusercontent.com/65140155/133006462-e8d458de-438d-4952-84a8-88e96414d78e.jpg)

**Comment by Dragonflysots** [comment]
fix
