### ISSUE TITLE
Kein Entkommen aus der Arena

### ISSUE THREAD

**Issue by xydragonxy** [pokemon-sots/pokemon-sots-issues#296]
**Beschreibe den Bug**
Wenn man einen Stein falsch schiebt kommt man nicht mehr aus der Arena

**Reproduzieren**
*Schritte, um den Bug auszulösen*
 Schiebe den Stein wie im Bild und man ist eingesperrt 

**Erwartetes Verhalten**
Man sollte immer aus der Arena können

**Screenshots**
![Arena Softlock](https://user-images.githubusercontent.com/65260349/133051300-1a3cee3d-08aa-4d2b-9760-470ad175bfa2.PNG)

**Verwendeter Emulator / Hardware**
vba-m 2.1.4

**Comment by Dragonflysots** [comment]
fixed
