### ISSUE TITLE
Kollision, Grafik und Layerfehler Klippen

### ISSUE THREAD

**Issue by xydragonxy** [pokemon-sots/pokemon-sots-issues#297]
1.Layerfehler an allen Bäumen im Wasser
2.Layerfehler an der Ecke
3.Layerfehler beim Schlamm evtl "ob es so muss keine ahnung"
4.Kollisionsfehler Markierung
5.Kollisionsfehler Markierung
6.Kolisionsfehler am Baum
7.Kollisionsfehler Markierung
8.Kollisionsfehler Markierung

**Screenshots**
![Klippen Layerfehler](https://user-images.githubusercontent.com/65260349/133119011-5723cf8d-02c0-40ea-b9ef-eaf630e05d15.PNG)
![klippen layerfehler1](https://user-images.githubusercontent.com/65260349/133119100-e832d4a5-7622-4405-92a4-02258696557e.PNG)
![Klippen Layerfehler2](https://user-images.githubusercontent.com/65260349/133119225-a06d5f75-df78-4e19-ab31-b134d8f67d7b.PNG)
![Klippen Kollisionsfehler](https://user-images.githubusercontent.com/65260349/133119436-eaf3fdb2-d29d-4217-955b-d27433840a83.PNG)
![Klippen Kollisionsfehler1](https://user-images.githubusercontent.com/65260349/133119498-21a2c35b-ce40-4713-9662-7209b4d20a16.PNG)
![Klippen Kollisionsfehler2](https://user-images.githubusercontent.com/65260349/133119582-f852f4b0-b265-4904-92d6-02f39b3070ed.PNG)
![Klippen Kollisionsfehler3](https://user-images.githubusercontent.com/65260349/133119721-e78f0b01-7b96-419f-a824-fc8a1c1529ee.PNG)
![Klippen Kollisionsfehler4](https://user-images.githubusercontent.com/65260349/133119872-ae0b623f-02ba-4ac6-8273-7eb1dd36c132.PNG)

**Verwendeter Emulator / Hardware**
*Welcher Emulator wurde verwendet, als der Bug auftrat?*

**Zusätzliche Information**
*Jegliche Information, die ansonsten noch nützlich sein könnte, um uns bei der Lösung des Problems zu helfen.*

**Comment by Dragonflysots** [comment]
fix
