### ISSUE TITLE
Poknav breaks sometimes in regards to the fishing rod

### ISSUE THREAD

**Issue by SBird1337** [pokemon-sots/pokemon-sots-issues#298]
**Describe the Bug**
Title

**Reproduce**
*Steps to reproduce*
1. Go to Safari Zone
2. Open Nav

**Expected Behavior**
* Fishing mons shown

**Screenshots**
/

**Used Emulator / Hardware**
vba-m

**Misc. Information**
/

**Comment by xydragonxy** [comment]
![Angel](https://user-images.githubusercontent.com/65260349/133167418-fb47f5db-d64c-421a-ac01-05d04dfde079.PNG)

**Comment by SBird1337** [comment]
fixed internally
