### ISSUE TITLE
Safari Zone Fehler

### ISSUE THREAD

**Issue by xydragonxy** [pokemon-sots/pokemon-sots-issues#299]
**Screenshots**
![Safari Kollision1](https://user-images.githubusercontent.com/65260349/133167298-99b45cc0-e9a0-46f9-af0f-27fd6be498c8.PNG)
![Safari Zone höhle Ausgang](https://user-images.githubusercontent.com/65260349/133167338-055d6be5-3190-4928-adc9-58df3ebc7971.PNG)
![Safari Zone höhle Surfen](https://user-images.githubusercontent.com/65260349/133167356-cc3d6e4f-b1ca-4ab4-b86f-bb2632e3ee2b.PNG)
![Safari Zone Kollision](https://user-images.githubusercontent.com/65260349/133167366-d5b15ecc-25f8-43f8-81c3-ed177e9ce7ea.PNG)

**Verwendeter Emulator / Hardware**
vba-m 2.1.4

**Comment by Dragonflysots** [comment]
fixed
