### ISSUE TITLE
Fehlender Text - Pokemon Center

### ISSUE THREAD

**Issue by 4Reddy** [pokemon-sots/pokemon-sots-issues#3]
*Bitte fülle dieses Template aus, und lösche vor dem Abschicken die Platzhalter, sowie diese Zeile.*

**Beschreibe den Bug**
Vor dem Pokemon Center steht schwester Joy. Wenn man sie anspricht redet sie nicht zu ende. Es wurde wohl einfach text vergessen

**Reproduzieren**
*Schritte, um den Bug auszulösen*
1. Gehe zum Pokemon Center bevor man sein 1.Pokemon besitzt
2. Rede mit Schwester Joy
3. Der Satz endet einfach nach:,,Pokemon-Center in Carun-City und Hesperia werden."

**Erwartetes Verhalten**
Vermutlich sollte der satz mit "und Hesperia werden momentan gewartet" enden

**Screenshots**
![IMG_20200510_232347](https://user-images.githubusercontent.com/65133519/81510925-e1327c80-9315-11ea-897b-027aea99ec05.jpg)

**Verwendeter Emulator / Hardware**
JohnGBA für android.

**Zusätzliche Information**
Da wurde einfach nur text vergessen ;)

**Comment by SBird1337** [comment]
War das bevor oder nachdem du ein Pokémon erhalten hast?

**Comment by 4Reddy** [comment]
Bevor ich mein erstes pokemon erhalte

**Comment by SBird1337** [comment]
Duplicate of #2
