### ISSUE TITLE
Bug Sammelthread Carun City

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#301]
**Describe the Bug**
Wenn ich den Professor anspreche, erscheint eine Textbox über ein Buch von Aiden statt eine Unterhaltung mit dem Npc.

**Reproduce**

1. Go to Carun City
2. Talk to the NPC seen in the screenshot

**Expected Behavior**
Vernünftige Gespräche

**Screenshots**
![Bug No1](https://user-images.githubusercontent.com/65140155/133302601-e052cab9-e1ff-43b3-b36a-82b924506999.jpg)

**Used Emulator / Hardware**
mGBA 0.9.2

**Comment by Dragonflysots** [comment]
fixed
