### ISSUE TITLE
(english version) Noah encounter on Path of Kalden

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#302]
**Beschreibe den Bug**
Wenn der Admin was testen will und ein Tester es ausbaden darf. xD

**Reproduzieren**
1. Beende den Wald von Yelnia.
2. Laufe durch die Höhle Richtung Pfad von Kalden
3. Auf dem Pfad von Kalden so lange nach links laufen, bis markierter Trainer mit dir kämpfen will

**Erwartetes Verhalten**
Kein Admin abuse :p

**Screenshots**
![zipfelklatscher](https://user-images.githubusercontent.com/65140155/133469281-a24c0a19-4701-49dc-bef2-0fb506ded410.jpg)
![zipfelklatscher2](https://user-images.githubusercontent.com/65140155/133469352-cfefd028-a4a5-4b36-9d4d-a35491e14d82.jpg)

**Verwendeter Emulator / Hardware**
mGBA 0.9.2

**Comment by Dragonflysots** [comment]
fixed
