### ISSUE TITLE
Bug Mt. Pass of Altera

### ISSUE THREAD

**Issue by xLiviusx** [pokemon-sots/pokemon-sots-issues#303]
**Beschreibe den Bug**
Markierter Bereich ist nicht begehbar. Laufe ich von rechts dagegen bekomme ich die normalen Sounds als würde ich gegen ne Wand laufen. Laufe ich aber von links dagegen hängt sich das Spiel grafisch als auch sound technisch auf bis ich nicht mehr dagegen laufe.

**Reproduzieren**
1. Betrete den Mt. Pass of Altera
2. Besiege den zu sehenden Npc
3. Laufe gegen die markierte Stelle

**Erwartetes Verhalten**
Offensichtlich begehbare Stellen sollten auch begehbar sein.

**Screenshots**
![Bugno1](https://user-images.githubusercontent.com/65140155/133475480-dab1b2c3-23eb-45dd-b1a6-3f7fb66c3ed2.jpg)

**Verwendeter Emulator / Hardware**
mGBA 0.9.2

**Comment by Dragonflysots** [comment]
alles korrekt

**Comment by ipatix** [comment]
Das sollte nicht so.

**Comment by Dragonflysots** [comment]
[ninjatrainer.sav.zip](https://github.com/pokemon-sots/pokemon-sots-issues/files/7245928/ninjatrainer.sav.zip)
@ipatix Ein Savegame

**Comment by Dragonflysots** [comment]
https://user-images.githubusercontent.com/27623565/135733830-8e16a864-b54f-4ab3-a898-bce98ff4d50c.mp4
[pokeemerald.sav.zip](https://github.com/pokemon-sots/pokemon-sots-issues/files/7272363/pokeemerald.sav.zip)

**Comment by ipatix** [comment]
b3005a94135aae965d691774211c91132ca90d96
