### ISSUE TITLE
Flackernder Bildschirm

### ISSUE THREAD

**Issue by ipatix** [pokemon-sots/pokemon-sots-issues#304]
**Beschreibe den Bug**
Bildschirm flackert und bunter Streifen ist zu sehen, wenn die Kamera zum Spieler zurückkehrt

**Screenshots**
https://user-images.githubusercontent.com/8502545/133890812-57f5bb4b-89d9-4b7e-add4-3213cfb74caa.mp4

**Verwendeter Emulator / Hardware**
mGBA, echter GBA

**Comment by Dragonflysots** [comment]
Das ist kein richtiges flackern sondern ganz normaler warp. Hab aber nen Fadescreen davor gesetzt.

**Comment by ipatix** [comment]
Naja, finde nen blauen Streifen mitten im Bild zu sehen jetzt nicht so korrekt.
