### ISSUE TITLE
Event Fehler

### ISSUE THREAD

**Issue by ipatix** [pokemon-sots/pokemon-sots-issues#305]
**Beschreibe den Bug**
Läuft man im Rebera Gebirge von rechts vor den Ruineneingang, passt irgendwas nicht im Gegensatz zur Mitte bzw links.

**Reproduzieren**
*Schritte, um den Bug auszulösen*
1. Siehe Gif

**Erwartetes Verhalten**
Das Event startet auch wenn man von rechts reinläuft.

**Screenshots**
![test](https://user-images.githubusercontent.com/8502545/133896518-5f3796f4-c56b-4d31-9289-34460ce4f8bd.gif)

**Verwendeter Emulator / Hardware**
mGBA / echter GBA

**Zusätzliche Information**
N/A

**Comment by Dragonflysots** [comment]
gefixt
