### ISSUE TITLE
YES/NO are capitalised in contrast to the rest of the game

### ISSUE THREAD

**Issue by Bassoonian** [pokemon-sots/pokemon-sots-issues#307]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927083-b24f645b-7fcb-4d06-a381-fc22847bba99.png">

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927830-542418c1-124f-4c98-8476-72565f968586.png">
Same applies to the battle commands

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927890-85e271a1-4145-4251-af90-551c8d1b2ecf.png">
I believe in modern games this is capitalised as "Exp. Points".

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927914-0096a6c1-c1ed-4e8b-aba0-c427c0c3b032.png">
*Lv. and *HP

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133928074-76e5e72c-d685-4a44-a11a-dc64911b3bae.png">

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133928089-83261f63-3a62-4049-b2a8-5cd831f7034a.png">

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133928159-33470885-52ec-4f2d-a84f-07e16730418a.png">
(Ideally, Trainer Card at the top should have a space in the English version)

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133928171-7aa6dafc-da2f-4d4d-bd33-fec29342bf9a.png">

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133928803-fd733770-d714-4006-83d0-d24f790c3c62.png">

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133936752-4de0a5dc-08b0-492e-85d9-8bc4635af77e.png">

**Comment by Dragonflysots** [comment]
fixed
