### ISSUE TITLE
(arguably) slight formatting error in intro screen

### ISSUE THREAD

**Issue by Bassoonian** [pokemon-sots/pokemon-sots-issues#308]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927113-4e6ec7d4-5c4d-4d39-8b90-de62d04cb735.png">
One could argue the arrow is one or two pixels too far right. May be personal preference, but figured I'd mention it regardless.

**Comment by Dragonflysots** [comment]
fixed
