### ISSUE TITLE
Typo in the trainer school

### ISSUE THREAD

**Issue by Bassoonian** [pokemon-sots/pokemon-sots-issues#309]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927166-62ccf7bf-2f3f-47d8-8f77-47af52857592.png">
*that's

-- Fixed

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927277-018d60b6-466a-455f-b8b7-c1d47d8d137c.png">
*that's (second floor)

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927358-e7911087-0fd6-43f6-aae9-7fa143e0f312.png">
*Trainer School

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927385-4c9a905d-c291-4930-a591-01d1adc9a12d.png">
I believe "dragon" should be capitalised here since it refers to the Dragon type.

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927408-8e0c3da4-7685-489d-8e04-b87cb4b7fa37.png">
Capitalisation of Munchlax

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927460-eb7c6fab-b57c-46d2-8ed4-b6175876d79a.png">
Presumably better in English as "Carun Tunnel"

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927499-a0729582-46b6-4451-a58a-f7614c0358b4.png">
Capitalisation of "Trainer"

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927538-7aab4c7d-bb22-48c1-945b-f095b5333b7f.png">
Capitalisation of "Berry"

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927627-81408915-0901-4c4b-a6a3-72597b38b20b.png">
*Poké Ball

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927651-9f1003a6-4452-43fe-87e1-5216b07ac5ee.png">
*than uncaptured/uncaught

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927738-2baf8fb7-72b9-44b9-a24f-eafb9dd0f06a.png">
*Pokémon Medicine. Also best to separate the sentences with a full stop rather than a comma

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927779-b8aaf66b-6fe0-49ca-bd89-8542195e646c.png">
*Poké Ball, as it is two words and there is also only one ball on the table

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927933-8755be12-b155-4e33-b19c-bd52c90f82fe.png">
*PKMN Trainer without the hyphen

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927971-06dcdc05-626d-4574-9a16-70872d4a8f7a.png">
Poké Mart

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133928011-d9486a41-cc81-4cfc-b2e4-142ea8bb17b3.png">
Capitalisation & formatting

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133928031-cc0cdec7-72a0-4f5d-93c7-22270e5bfbff.png">
[Pokémon] Storage System is traditionally capitalised

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133928043-1041ded1-bb37-4ea4-98ef-fd57a5c7bc46.png">
*Center

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133928098-785a85d7-77cf-42f4-b7e2-3b43b5b8bb0d.png">
*Nurse Joy in English. Also *Trainer

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133928244-1f3d61c8-fc30-46e6-ac75-57b26bdf180a.png">
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133928249-8068821b-f883-4d89-b016-a649de809acc.png">
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133928259-49f30a32-7a1b-4585-8628-326ac17ae64c.png">
Capitalisation for all types. Also, "Dark-type Pokémon"

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133928308-ebe8b291-e8cc-4944-bb6d-22ffd01fa86c.png">
*Berries

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133928350-b63b02c9-0988-4cb0-8fc9-155f1cafebb1.png">
*Trainer. Probably best to do a global search for "trainer" and capitalise where necessary because this keeps popping up everywhere.

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133928425-af654289-149a-4a59-a6e3-be4b0132efd3.png">
*they

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133928513-f6db400a-58c6-4956-8af2-2889990c962d.png">
Also a recurring formatting issue

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133928539-399a5384-7caf-4c49-9a82-0917d66f9382.png">
Strictly speaking, the correct capitalisation is PlayStation

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133928588-72cbada4-d56e-4a4b-93a8-b0520215f698.png">
Capitalisation, but also not the correct English description (translated literally for German seemingly)

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133929088-7a6d85e1-f610-409f-809f-ebb5b38b326b.png">
No hyphen required.

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133929141-c955b488-d1b3-44f0-aa8b-589b239f7e24.png">
*it's. The use of the acute is also unusual here in English (it would sooner capitalise the entire word)

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133929318-d2b149d4-bb36-4643-8bf5-42ce057f4f53.png">
*Pleasant

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133929349-297add5e-5bd8-4014-b7e7-27d7a3d34064.png">
*PokéNav, *DexNav

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133929376-7b5654c9-967e-4595-9e3e-0d4ce9df9cfa.png">
The item was called "Itemfinder" (which is its correct English name) in the previous "Player received the Itemfinder" message

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133929450-334c78ff-e7dd-49e5-97c7-2da8fa9ceeb4.png">
Frau seems to be a leftover from German

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133935437-7bb5de09-6efd-4193-bdd2-52128a36e11a.png">
*Wormadam

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133935458-04b28701-16c7-4f30-bfe6-309983cb49b8.png">
Shouldn't this be Path of Yelnia?

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133936480-897ea26b-9807-4854-a85c-9063ec22c5f1.png">
no hyphen required (technically, bird should also be uncapitalised since it's not a type)

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133936589-3b2eb851-f73d-46e2-bccd-71a56efb8198.png">
*keeper (Keeper?) presumably

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133936859-4c2c9264-1e6f-4c1f-930f-87b1d31530fb.png">
Bird Pokémon (see also above) really feels like an obsolete term

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133936909-94783b13-3a52-4bba-bc7c-513023f78858.png">
Probably better as the stylised PKMN

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133936951-2ab1f8d9-cd9c-4d46-9ccf-ba54a5721b56.png">
Capitalisation and punctuation

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133937003-9fcbd911-f239-4c4a-9622-649c3bcf88c5.png">
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133937008-525419b8-491b-433b-a4f3-a32e3f8ee061.png">

Lack of capitalisation consistency

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133937041-836ad5ee-9b31-48f9-aaef-1ac3ad2b055d.png">
*Potion, *Pokémon Center (the abbreviation is not standard practice in English)

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133937104-0b90960e-ef7e-4556-84fa-b517d36297c5.png">
Capitalisation

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133937117-fd6e06e9-28a5-4ac5-8195-522035fa4467.png">
Capitalisation

**Comment by Dragonflysots** [comment]
@SBird1337 Das fixen wir dann wenn die korrigierten Texte kommen, dann kann man auf Grundlage dessen fixen.
