### ISSUE TITLE
Identical dialogue in the first floor of the Trainer School

### ISSUE THREAD

**Issue by Bassoonian** [pokemon-sots/pokemon-sots-issues#310]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927219-84ffb753-eef6-4f3f-976e-c65c2e21d446.png">
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927250-64d819c4-685d-423e-9bd1-ada9e309feba.png">

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927262-0f33fe52-b827-4bca-ae19-49fe93cd2ea9.png">
Also applies to the girl here.

**Comment by Dragonflysots** [comment]
fixed
