### ISSUE TITLE
Identical dialogue in the lab

### ISSUE THREAD

**Issue by Bassoonian** [pokemon-sots/pokemon-sots-issues#311]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927763-122750d9-f21c-4991-84df-d65da2f4ba8c.png">
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927768-9557b440-9899-4b7b-afe6-4dcb52acacf5.png">

**Comment by Dragonflysots** [comment]
fixed
