### ISSUE TITLE
Mega Stones formatting in bag

### ISSUE THREAD

**Issue by Bassoonian** [pokemon-sots/pokemon-sots-issues#312]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927843-66794c2a-7426-47b6-854e-a4fab65b05c4.png">
*Mega Stone, but the plural form has the end of the s cut off. This then causes another minor graphical glitch in the next pocket:
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133927860-ff921733-67cb-4c6a-91e6-c90d31bb5aae.png">

**Comment by Dragonflysots** [comment]
fixed
