### ISSUE TITLE
Untranslated German

### ISSUE THREAD

**Issue by Bassoonian** [pokemon-sots/pokemon-sots-issues#313]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133928125-36b25812-a69b-482b-ad15-e5c3abdfaf95.png">
Ges. and Gef. should be translated (why are they abbreviated in German? Don't they fit otherwise?)

**Comment by SBird1337** [comment]
they where abbreviated in the original, I guess I just left it that way and could easily write the full strings when I fix the translation oversight

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133929410-835db807-3b27-4d4e-9fd2-8bb95e19eed2.png">
More untranslated German here

**Comment by Dragonflysots** [comment]
fixed
