### ISSUE TITLE
Start Menu is invisible in East Rebera Mountain

### ISSUE THREAD

**Issue by Bassoonian** [pokemon-sots/pokemon-sots-issues#314]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133928821-2e16deeb-6589-4708-9c50-4c629099c560.png">
Pressing start here gives a black screen. The start menu remains functional as pressing A again opens the Pokedex for example and it does not freeze the game, but this remains a major issue regardless

**Comment by Bassoonian** [comment]
It is worth noting that after seeing the cutscene with the motion sensors, the start menu is visible again like normal.

**Comment by Dragonflysots** [comment]
fixed
