### ISSUE TITLE
Identical dialogue in Path of Yelnia

### ISSUE THREAD

**Issue by Bassoonian** [pokemon-sots/pokemon-sots-issues#315]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133935398-79b86a40-6bd6-4e34-9c33-a36c0c5f5b51.png">
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133935403-01e5bea3-3cda-4ea1-9619-0436c37c03cd.png">

**Comment by Dragonflysots** [comment]
fixed
