### ISSUE TITLE
Sylviria City duplicate dialogue

### ISSUE THREAD

**Issue by Bassoonian** [pokemon-sots/pokemon-sots-issues#319]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133936881-2a06f1c0-75f3-4215-bb92-70d994cfb28f.png">

Apparently the NPC is empty too

**Comment by Bassoonian** [comment]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/16993385/133936970-f9600954-3c97-4010-b1f1-d3a975957ad6.png">

The same text appears in another house

**Comment by Dragonflysots** [comment]
fixed
