### ISSUE TITLE
Falscher Sprite für Taubsi

### ISSUE THREAD

**Issue by 4Reddy** [pokemon-sots/pokemon-sots-issues#32]
**Beschreibe den Bug**
Falscher Minisprite für Taubsi in der Pokemon Team übersicht und bei der Spitznamen vergabe

**Reproduzieren**
1. Fange Taubsi und vergebe spitznamen
Oder
2. Sehe dir dein pokemon team an

**Erwartetes Verhalten**
Richtige farbe des Sprite

**Screenshots**
![IMG_20200511_130223](https://user-images.githubusercontent.com/65133519/81555081-2abbaf80-9388-11ea-8992-cc26b2d9a21c.jpg)
![IMG_20200511_130243](https://user-images.githubusercontent.com/65133519/81555099-2ee7cd00-9388-11ea-9f83-441387a5541b.jpg)

So stelle ich es mir vor
![IMG_20200511_130258](https://user-images.githubusercontent.com/65133519/81555123-3b6c2580-9388-11ea-9809-78f2d6489622.jpg)

**Verwendeter Emulator / Hardware**
MyBoy auf Android

**Zusätzliche Information**

**Comment by SBird1337** [comment]
Ich vermute mal, due to lack of farben, wird der Taubsi sprite nicht näher am Original sein können, als er es schon ist.
