### ISSUE TITLE
Walking into Forest of Yelnia after meeting Evelyn on the Tree of Life shows no location sign

### ISSUE THREAD

**Issue by Bassoonian** [pokemon-sots/pokemon-sots-issues#322]
No "Forest of Yelnia" pop-up when switching to the forest map. Going back into Sylviria has Sylviria pop up, however. This is in stark contrast with the recurring "Forest of Yelnia" pop-ups inside the forest when crossing map boundaries, which is non-Nintendo behaviour.

**Comment by Dragonflysots** [comment]
fixed
