### ISSUE TITLE
Wasseranimation Futsch MS Primarane

### ISSUE THREAD

**Issue by Dragonflysots** [pokemon-sots/pokemon-sots-issues#324]
https://user-images.githubusercontent.com/27623565/135126834-55a814bf-1a37-45aa-bbfd-d6e4cc6a7d80.mp4

**Comment by Dragonflysots** [comment]
Ein Savegame:
[wasserstrahl savegame.sav.zip](https://github.com/pokemon-sots/pokemon-sots-issues/files/7245933/wasserstrahl.savegame.sav.zip)

**Comment by ipatix** [comment]
savegame passt nicht

**Comment by Dragonflysots** [comment]
@ipati
[wasseranimation.sav.zip](https://github.com/pokemon-sots/pokemon-sots-issues/files/7246337/wasseranimation.sav.zip)
x

**Comment by ipatix** [comment]
fixed 1a84eec4509fc0fcd02cfc415e2f49067952722c
