### ISSUE TITLE
Meeresrauschen Random Indoor

### ISSUE THREAD

**Issue by Dragonflysots** [pokemon-sots/pokemon-sots-issues#325]
https://user-images.githubusercontent.com/27623565/135126942-ae94fec1-5dc1-490d-9e9e-8e221b253e84.mp4

**Comment by Dragonflysots** [comment]
[meeresrauschen.sav.zip](https://github.com/pokemon-sots/pokemon-sots-issues/files/7245915/meeresrauschen.sav.zip)
Hier ein Savegame

**Comment by ipatix** [comment]
2638ed056f9e5e46943ec2e5da013b8d949cfae0
