### ISSUE TITLE
Ninjatrainer (Berg Tarnung) defekt

### ISSUE THREAD

**Issue by Dragonflysots** [pokemon-sots/pokemon-sots-issues#326]
https://user-images.githubusercontent.com/27623565/135127107-9d866169-f9f5-4c91-9ab5-b349e05e3073.mp4

**Comment by Dragonflysots** [comment]
[ninjatrainer.sav.zip](https://github.com/pokemon-sots/pokemon-sots-issues/files/7245922/ninjatrainer.sav.zip)
Ein Savegame

**Comment by ipatix** [comment]
e86234fef89f13ba268359f838c6c76134d84ca3
