### ISSUE TITLE
Fehlende Soundtracks für die Beta

### ISSUE THREAD

**Issue by Dragonflysots** [pokemon-sots/pokemon-sots-issues#328]
- [x] Kammern von Taran (High prio)
- [x] Altera Minen (Normal prio)
- [x] Wild Pokémon Theme (Low Prio)

**Comment by Dragonflysots** [comment]
@ipatix Wenns ingame eingefügt ist, kannste das hier closen.

**Comment by ipatix** [comment]
e2edb6c955d1f8f80ef454022b872f201975f73f
