### ISSUE TITLE
Fehlender Pokedex eintrag Alola Rattfratz

### ISSUE THREAD

**Issue by 4Reddy** [pokemon-sots/pokemon-sots-issues#33]
![IMG_20200511_140343](https://user-images.githubusercontent.com/65133519/81559932-a883b900-9390-11ea-96ee-705bc728d032.jpg)

**Beschreibe den Bug**
Fehlender Pokedex eintrag für Alola Rattfratz

**Reproduzieren**
*Schritte, um den Bug auszulösen*
1. Fange Alola Rattfratz
2. Sehe dir den Pokedex eintrag an der automatisch angezeigt wird wenn man es das erste mal fängt

**Erwartetes Verhalten**
Richtig stellung des eintrages

**Screenshots**
![IMG_20200511_140120](https://user-images.githubusercontent.com/65133519/81559912-a02b7e00-9390-11ea-95c2-66338fc272d6.jpg)
![IMG_20200511_140130](https://user-images.githubusercontent.com/65133519/81559927-a6215f00-9390-11ea-8452-ee7b9cfdddb5.jpg)

**Verwendeter Emulator / Hardware**
MyBoy für android

**Zusätzliche Information**

**Comment by SBird1337** [comment]
das mon sollte sich einen eintrag mit rattfratz teilen, was es wohl aktuell noch nicht tut.

**Comment by Dragonflysots** [comment]
Vorläufig wurde Alola-Rattfratz rausgenommen. Die Alola Pokémon haben noch keine richtigen Einträge. Alola Rattfratz war bisher das einzige im Spiel, wird sicher nach der Alpha wiederkommen.
