### ISSUE TITLE
Spieler kann durch NPCs durchlaufen

### ISSUE THREAD

**Issue by Dragonflysots** [pokemon-sots/pokemon-sots-issues#332]
**Beschreibe den Bug**
Der Spieler kann (siehe Video) random durch NPCs durchlaufen, obwohl die Collisions und Z-Achse auf dieser Map völlig korrekt ist.

**Reproduzieren**
1. Gehe in Sylviria City in das Haus mit den Kindern und Zigzachs und verfahre wie im Video. (Es ist nicht immer reproduzierbar).
2. Laufe dann runter im richtigen moment in den NPC.

https://user-images.githubusercontent.com/27623565/135756505-090a2e69-5ca9-464f-9af8-c1c5ac9c56e7.mp4

**Comment by Dragonflysots** [comment]
grund vorerst nicht nachvollziehbar

**Comment by Dragonflysots** [comment]
https://user-images.githubusercontent.com/27623565/135767213-c68946db-e734-4eca-a0f8-ea31af08cfb6.mp4

Das ist definitiv so nicht ok…

**Comment by ipatix** [comment]
9facebedf373a0e6002a334fb36990fb4e8907f1
