### ISSUE TITLE
Kletteranimation mit Warp buggt.

### ISSUE THREAD

**Issue by Dragonflysots** [pokemon-sots/pokemon-sots-issues#338]
Das Behaviour MB_CLIMB_SOUTH_ARROW_WARP verhindert beim Klettern nicht, dass der Spieler seine Blickrichtung nach Links/Rechts dreht siehe Video.

https://user-images.githubusercontent.com/27623565/136599262-cb5d07b1-6d98-41cd-bb36-6ed2d86b23e3.mp4

**Comment by SBird1337** [comment]
62b7f14fe5e847c6b6075345034b2ebb67a547e7
