### ISSUE TITLE
Falscher minisprite Hornliu

### ISSUE THREAD

**Issue by 4Reddy** [pokemon-sots/pokemon-sots-issues#34]
**Beschreibe den Bug**
Falscher minisprite von Hornlio in der Pokemon Team übersicht und bei der vergabe von spitznamen. Der minisprite ist Shiny obwohl hornliu nicht shiny ist

**Reproduzieren**
1. Fange Hornliu
2. Rede mit dem auf dem Bild zu sehenden NPC
3. Der Bildschirm färbt sich pink und das Spiel stürzt ab.

**Erwartetes Verhalten**
Korrekter minisprite

**Sceeenshots**
![Screenshot_2020-05-11-16-53-35-732_com fastemulator gba](https://user-images.githubusercontent.com/65133519/81576386-7e3df580-93a8-11ea-8db7-93e92ff91faf.jpg)
![Screenshot_2020-05-11-16-53-44-662_com fastemulator gba](https://user-images.githubusercontent.com/65133519/81576401-8138e600-93a8-11ea-9e32-712536c35c30.jpg)
![Screenshot_2020-05-11-16-53-51-811_com fastemulator gba](https://user-images.githubusercontent.com/65133519/81576413-85650380-93a8-11ea-83ea-0dc99d3e322a.jpg)

**Verwendeter Emulator / Hardware**
MyBoy für Android

**Zusätzliche Information**

**Comment by SBird1337** [comment]
Ich vermute mal bei den Steps to reproduce ist noch ein Teil ausm Template drin :)
