### ISSUE TITLE
NPCs können nicht mehr durch die Befehle disable_anim und restore_anim gesteuert werden.

### ISSUE THREAD

**Issue by Dragonflysots** [pokemon-sots/pokemon-sots-issues#341]
Das hatten wir ja bereits besprochen, dass man die Frames nicht deaktivieren kann (für diese Teleport oder Schwebe effekte)
![pokeemerald-2](https://user-images.githubusercontent.com/27623565/136713755-7b225978-f967-42c5-bc4a-82e5f13b3c42.png)

**Comment by SBird1337** [comment]
`freeze_anim` vs. `unfreeze_anim`

776fbdf1c1b69e9e378ece154361a411dcf017d0
