### ISSUE TITLE
Detektoritems nicht auffindbar

### ISSUE THREAD

**Issue by mikedmei** [pokemon-sots/pokemon-sots-issues#358]
Heyho,
hab gerade ein weiteres Item gefunden welches vom Detektor angezeigt aber nicht auffindbar ist.
![SafariItem](https://user-images.githubusercontent.com/93452495/139558671-6765668f-320a-464d-af1f-b51a1d15125c.png)
Ein weiteres Item war in der Stadt mit der Pension(Sry Name gerade entfallen^^°) bei der Dame auf der Bank neben der Laterne...
bin gerade zu weit weg um ein Screen zu machen, werde ich aber später noch anhängen.

Falls ich noch mehr finde schreibe ich
Lg
MikeDMei

**Comment by Dragonflysots** [comment]
Bereits gefixt, kommt im Hotfix
