### ISSUE TITLE
Outdoor Pokémon als gesehen im Dex eintragen.

### ISSUE THREAD

**Issue by Dragonflysots** [pokemon-sots/pokemon-sots-issues#359]
![SPOILER_unknown-1](https://user-images.githubusercontent.com/27623565/139559058-fcdf38ab-123c-4b40-b535-57e2a7e13abd.png)
![SPOILER_unknown](https://user-images.githubusercontent.com/27623565/139559060-30187344-3bcf-42da-9f47-d99746ae784f.png)

**Comment by SBird1337** [comment]
b22e1b821911f0388ba75b757d153c5c9851d300
