### ISSUE TITLE
Sawsbuck missing name

### ISSUE THREAD

**Issue by mluizvitor** [pokemon-sots/pokemon-sots-issues#362]
**Describe the Bug**
Until the moment Deerling is evolving, all seems alright. But when it turns into Sawsbuck, the congratulations message shows a big blank space and 'tornadus'.
In Pokémon menu as in battles, Sawsbuck has a blank name.

I tried to change its name with the Name Rater on Mizeria City. The game just crashed.

**Reproduce**
Capture a Deerling, train it, evolve it.

**Screenshots**

| Evolving Screen | Battle and Menu | Name Rater | 
| ----- | ----- | ----- |
| ![Pokemon Sovereign of the Skies-211030-131114](https://user-images.githubusercontent.com/57257682/139558243-1cd8dfd3-e334-4b50-be1b-5874af8360fd.png) | ![Pokemon Sovereign of the Skies-211030-215231](https://user-images.githubusercontent.com/57257682/139562424-d076bd65-c838-492d-918a-e7e19afdab6a.png) | ![Pokemon Sovereign of the Skies-211030-185657](https://user-images.githubusercontent.com/57257682/139559586-6f685952-a9e8-436e-ad7a-4fe42de40b9f.png) |
| ![Pokemon Sovereign of the Skies-211030-131237](https://user-images.githubusercontent.com/57257682/139558248-29a09e33-fc35-498e-a497-ca73bc19cdb2.png) | ![Pokemon Sovereign of the Skies-211030-171332](https://user-images.githubusercontent.com/57257682/139558260-2be8ecb6-7a41-4e34-806c-64cc742fb9e4.png) | *black screen* |

**Used Emulator / Hardware**
I'm using mGBA core, RetroArch, 351elec operating system / I'm playing on an Anbernic RG351M

**Misc. Information**
I was on Safari Zone, after 1pm (local time) when Deerling evolved.
It was holding an Exp. Share

**Comment by Dragonflysots** [comment]
Name Rater is fixed.
