### ISSUE TITLE
Path of Iyasu MAP

### ISSUE THREAD

**Issue by Spekzu** [pokemon-sots/pokemon-sots-issues#363]
*By Riza~*

**Describe the Bug**
*Doesn't properly apear in the map.*

**Reproduce**
*Steps to reproduce*
Go to the area  in the screenshot`

**Expected Behavior**
*Self Explanatory*

**Screenshots**
*
![image](https://user-images.githubusercontent.com/76877306/139560555-1249b5a6-210b-493e-9340-087aa2282886.png)

![image](https://user-images.githubusercontent.com/76877306/139560560-2cb96b9c-656b-4eb9-9963-e63364165d6a.png)
*

**Used Emulator / Hardware**
*VBA-M

**Misc. Information**
*The bug is self explanatory*

**Comment by Dragonflysots** [comment]
Fixed in the Hotfix
