### ISSUE TITLE
Typo Bug report: Incorrect name in namebox

### ISSUE THREAD

**Issue by GhostofPink** [pokemon-sots/pokemon-sots-issues#364]
**Describe the Bug**
Tönfa's name appears in his namebox incorrectly during the conversation exchange when you reach the final room of the montera dojo

**Reproduce**
1. Defeat all the trainers in montera dojo
2. Enter the final room
3. Check the screenshots

**Change to**
Tönfa

**Used Emulator / Hardware**
*My Boy

![Pokemon Sovereign of the Skies_1635813629919](https://user-images.githubusercontent.com/93560640/139770810-a4d5e042-ffd7-43c1-b18a-4a5024e5797f.png)
![Pokemon Sovereign of the Skies_1635813629919](https://user-images.githubusercontent.com/93560640/139770812-c76ac897-92db-4c5e-adb3-573aa74fa8c7.png)
![Pokemon Sovereign of the Skies_1635814014968](https://user-images.githubusercontent.com/93560640/139770813-5bf332d0-a68c-4ab0-8c5c-eef0aa7583aa.png)
![Pokemon Sovereign of the Skies_1635813543212](https://user-images.githubusercontent.com/93560640/139770814-c684f34d-f8fc-4898-86f2-4e9fde0492e6.png)
![Pokemon Sovereign of the Skies_1635813555022](https://user-images.githubusercontent.com/93560640/139770815-5003502f-cd8b-4682-a9f2-820ba9de3b81.png)
![Pokemon Sovereign of the Skies_1635813521340](https://user-images.githubusercontent.com/93560640/139770816-fa3c9f9c-e90b-45b0-a4a9-74858a67c2ca.png)
![Pokemon Sovereign of the Skies_1635813547669](https://user-images.githubusercontent.com/93560640/139770817-a69278a7-a0bf-4949-a988-a277026136cf.png)
![Pokemon Sovereign of the Skies_1635814241461](https://user-images.githubusercontent.com/93560640/139770819-a0a88898-3e1e-4928-869e-33a3430fe9a8.png)

**Comment by SBird1337** [comment]
a6fa7cdb7d6f185e046c7adecf3fa29ba188fc3b
