### ISSUE TITLE
Araji Statuen Puzzle

### ISSUE THREAD

**Issue by amachairidis** [pokemon-sots/pokemon-sots-issues#366]
Ich weiß nicht ob es alle Statuen Rätsel betrifft. (Nicht das Ying Yang, sondern Statue auf Knopf schieben)

Aber bei dem letzten konntest du die Statue ins Loch fallen lassen und beim nächsten Schubs kam sie wieder raus und du konntest weitermachen. Bin so durch das letzte Rätsel gekommen ohne es „offiziell“ zu lösen. 

Wenn die Statue wieder rauskommt sitzt sie sogar auf dem „Loch“. Somit kannst du es immer 1 weiterschieben bevor es wieder reinfällt. 

habe auf Delta (iOS) gespielt. Ist aber glaube ich egal.

**Comment by Dragonflysots** [comment]
Bereits gefixt
