### ISSUE TITLE
Übersetzungsfehler beim Fangen von Pokemon in der englischsprachigen Version zurück?

### ISSUE THREAD

**Issue by JohnGoten** [pokemon-sots/pokemon-sots-issues#367]
https://github.com/pokemon-sots/pokemon-sots-issues/issues/340#

Sobald ein Pokemon mit vollem Team gefangen wird, erscheint die deutschsprachige Nachricht, dass dieses auf dem PC gelagert wurde.
![visualboyadvance-m_mAQYVbOkLh](https://user-images.githubusercontent.com/92606827/140429743-3e27287d-ae3d-4c23-8792-2051897a2764.png)

VBA-M, SotS v2.1.1
**Pokemon - Emerald Version (USA, Europe).gba**    (_ich gehe mal davon stark aus, dass diese trotz des "Europe" tags kompatibel sein sollte_)
CRC32:
1f1c08fb
MD5:
605b89b67018abcea91e693a4dd25be3
SHA-1:
f3ae088181bf583e55daf962a92bb46f4f1d07b7

**Comment by Dragonflysots** [comment]
Bereits gefixt
