### ISSUE TITLE
Berries don't grow

### ISSUE THREAD

**Issue by mluizvitor** [pokemon-sots/pokemon-sots-issues#368]
**Describe the Bug**
Berries just don't grow. I've been playing for about two weeks now, I've completed the post 3rd emblem events. I water the berries I planted every day and they don't pass the seed stage.

**Reproduce**
1. Harvest a berry, plant it and water it.
2. Wait 3 hours, no change.
3. Go back to step 2

**Expected Behavior**
Sturmvogel pointed out in Discord that the berries system should follow the same as Pokémon Emerald. In general each stage should last 3 hours. But they never get past the first stage.

**Screenshots**
I can prove with screenshots only that the berries system works well in Pokémon Emerald using the same device and emulator I use to play SotS.
At the top of the screenshot you can see the moment they were taken.

| ![Captura de ecrã de 2021-11-08 18 37 08](https://user-images.githubusercontent.com/57257682/140827135-a9f06952-b289-429a-ab77-07932761c4d5.png) | ![Captura de ecrã de 2021-11-08 18 37 55](https://user-images.githubusercontent.com/57257682/140827166-4bdb138d-ec86-4b4a-9960-29d00dfff4d3.png) |
| :--------------------------: | :--------------------------: |
| 08/11/2021 15:29:10 | 08/11/2021 18:31:32 |

**Used Emulator / Hardware**
Using mGBA core, RetroArch, 351elec operating system / Playing on an Anbernic RG351M

**Comment by SBird1337** [comment]
turns out time based events were initialized but reset due to the intro being so early in the games state.

Fixed by 9dcb067045a7e31d04196c538a48fa349164f654
