### ISSUE TITLE
Leiter kann man nicht hochklettern(Arena diana) 

### ISSUE THREAD

**Issue by reini06** [pokemon-sots/pokemon-sots-issues#370]
Wenn ich in der Arena von der arenaleiterin Diana bin, kann ich beim dritten Rätsel die Leiter nicht hochklettern. ich bleibe beim hochklettern hängen. 

Emulator:MyBoy! Free(Android) 

Emulator neugestartet - ohne Änderung

**Comment by reini06** [comment]
![Screenshot_20211120_103611_com fastemulator gbafree](https://user-images.githubusercontent.com/85752908/142721871-1444c3d9-3414-4d92-b177-bfc4fe4671f2.jpg)

**Comment by Mcsundae125** [comment]
Ist bei mir auch so :( schon beim zweiten Rätsel... gibt es eine Lösung? Oder ist der Spielstand jetzt einfach tot? Hatte leider genau dort gespeichert und hänge jetzt da unten fest...

**Comment by SBird1337** [comment]
Hi, wenn ihr bei uns im Discord seid und das Problem noch habt, könnt ihr dem @Dragonflysots einen Spielstand schicken und er kann euch das Problem lösen, in der nächsten Version ist es dann gefixt.

**Comment by Mcsundae125** [comment]
Das klingt schonmal gut!!
Ich muss nur sagen, dass ich ein ziemlicher noob bin was das alles angeht ^^' kenne euren Discord Channel nicht und bin auch nicht sicher, ob ich weiß wo mein Spielstand aufm Handy gespeichert ist xD ...kannst du mir da weiterhelfen?

**Comment by Dragonflysots** [comment]
bereits gefixt, kommt mit dem hotfix

**Comment by Mcsundae125** [comment]
Oh Wunderbar! :) 

Ich habe versucht Dragonfly auf Discord meinen Spielstand zu schicken, aber kann ihn nicht kontaktieren? 
Im FAQ steht, dass der Speicherstand nicht in neuen Versionen übernommen werden kann...?
