### ISSUE TITLE
Treecko typo

### ISSUE THREAD

**Issue by soapfaucet** [pokemon-sots/pokemon-sots-issues#371]
In the battle against the water/electric leader, if you chose froakie, then the "rival" still says treecko when the sprite is of a grovyle.

1. pick froakie as starter
1. go to the water gym
3. complete puzzles
4. your sibling says treecko instead of grovyle.

it should say grovyle since the overworld sprite is one and no longer a treecko

![Screen Shot 2021-11-26 at 5 09 45 PM](https://user-images.githubusercontent.com/95140105/143689243-efb39177-91f0-4b41-a0c4-66416fcf3449.png)

OpenEmu on Mac

idk, choose froakie. i guess?

**Comment by Dragonflysots** [comment]
fixed
