### ISSUE TITLE
Typo at the professor's lab

### ISSUE THREAD

**Issue by Importantamigo** [pokemon-sots/pokemon-sots-issues#373]
**Describe the Bug**
*A typographical error in the word 'pleasant'*

**Reproduce**
*Steps to reproduce*
It happens during some story text so it can't be reproduced without a new save file
1. complete the whole Hesperia ruins stuff at the start.

**Expected Behavior**
*When teleported back to the lab after the ruins collapse, the text has a typo in it*

**Screenshots**
*
![1986 - Pokemon SOTS_1639292736250](https://user-images.githubusercontent.com/88456081/145753028-211478eb-5003-424b-a5c9-83b3981b6af0.png)

**Comment by Dragonflysots** [comment]
fixed
