### ISSUE TITLE
Wrong location name

### ISSUE THREAD

**Issue by GhostofPink** [pokemon-sots/pokemon-sots-issues#374]
*Please fill out this template and delete any filler texts as well as this line.*

**Describe the Bug**
*Typo Bug...sign at Rebera Path points to the wrong location

**Reproduce**
1. Go east from Path of Rebera
2. Check the sign
3. The sign will say -> Path of Kalden
4.  Keep going East 
5. You are at Road of Kalden

**Expected Behavior**
*Sign should say   -> Road of Kalden

https://user-images.githubusercontent.com/93560640/145900068-3775bef6-f1ca-4129-bc03-88335dd5ef11.mp4

**Used Emulator / Hardware**
*My Boy

**Misc. Information**
*Any additional information to help us track down the bug.*

**Comment by Dragonflysots** [comment]
fixed
