### ISSUE TITLE
Stuck in SS Primarina, game breaking glitch

### ISSUE THREAD

**Issue by gitboybitboy** [pokemon-sots/pokemon-sots-issues#375]
Saved the game while doing the mirror puzzle in the pool of water, when i loaded the game the ladder is locked and i cannot leave the puzzle area. gamebreaking glitch and i would prefer not to start a new game if you could help me out. when i climb the ladder to leave the puzzle area the ladder is locked. potential patch unlocking the ladders permanantly?

**Comment by SBird1337** [comment]
duplicate of #370

**Comment by Mcsundae125** [comment]
Its the Same for me! I'm really emotionally attached to the save File :( 
How can i get out of this?
