### ISSUE TITLE
Poisonpowder doesn't affect Grovyle

### ISSUE THREAD

**Issue by meltingkeith** [pokemon-sots/pokemon-sots-issues#382]
**Describe the Bug**
When fighting a Paras in the Tree of Life, it kept using poisonpowder on my Grovyle. However, it never worked, and I kept getting the text, "it doesn't affect Grovyle".

**Reproduce**
1. Fight Paras with Grovyle
2. Wait for Paras to use poisonpowder
3. Resist

**Expected Behavior**
Grovyle should get poisoned

**Screenshots**
N/A

**Used Emulator / Hardware**
MyBoy on a Pixel 5

**Misc. Information**
N/A

**Comment by SBird1337** [comment]
Sovereign of the Skies battle mechanics are all based on gen7. As can be read in this article: https://m.bulbapedia.bulbagarden.net/wiki/Category:Powder_and_spore_moves#:~:text=These%20moves%20are%20based%20on,are%20immune%20to%20these%20moves

The behavior is to be expected, grass-type mons are immune to spores.
