### ISSUE TITLE
Black Sky On East Rebera Mt.

### ISSUE THREAD

**Issue by kalebpikachu10** [pokemon-sots/pokemon-sots-issues#383]
I Just Saved The Game On East Rebera Mt. But When I Came Back The Whole Sky Is Black Can You Fix It Please. Here A Screenshot For Prove

![IMG_0091](https://user-images.githubusercontent.com/102438987/160258996-aa1f1a6d-5c41-4e4f-8de2-50ee016b6a75.PNG)

**Comment by SBird1337** [comment]
Will be fixed in the next major release. (commit hash 134ffb3634bdbd1e40b151631ac8165e05e389ed)
