### ISSUE TITLE
I can't progress in the game I am not sure if this is a glitch 

### ISSUE THREAD

**Issue by Ehnvm** [pokemon-sots/pokemon-sots-issues#387]
I did complete the whole 4×4 puzzle and the door just won't open . I have completed all the other puzzles before this and this one just won't work for some reason , here are some screenshots 
![Screenshot_2022-04-06-17-51-03-97](https://user-images.githubusercontent.com/103119095/161973587-436d6097-a09a-4943-a76d-05c79fd19d0a.png)
![Screenshot_2022-04-06-17-51-00-58](https://user-images.githubusercontent.com/103119095/161973595-777c32e6-50b6-4de4-bd94-09b4c70069d9.png)
Would appreciate a fix on this (if it is a bug) if it's not a bug please let me know what have I done wrong

**Comment by SBird1337** [comment]
from what I can see you placed the things one too low? Does not look like a bug to me :)
