### ISSUE TITLE
Time is 1 minute slower

### ISSUE THREAD

**Issue by Yave-Yu** [pokemon-sots/pokemon-sots-issues#390]
The RTC in game is 1 minute slower than real time.

Also a request: could you make greenish-early shorter? I think it should be ended up 8:59:59 then change to no-color-filter day.

**Comment by SBird1337** [comment]
Hi, we are not controlling the real time chip, it's either your hardware (flashcard) that has a skewed clock or your emulator (phone/pc) - The game just requests reads from the RTC hardware (Emulator or Hardware, either way)

**Comment by Yave-Yu** [comment]
I see.
