### ISSUE TITLE
???? Item erhalt - Sylivia (Wald Stadt)

### ISSUE THREAD

**Issue by 4Reddy** [pokemon-sots/pokemon-sots-issues#44]
**Beschreibe den Bug**
Wenn man in einem Haus in Sylivia einen schrank durchsucht findet man das Item ??????

**Reproduzieren**
1. Gehe nach Sylivia
2. Gehe in das Haus Links neben dem Bauernmarkt
3. Gehe in das obere stockwerk und klicke den schrank rechts oben an

**Erwartetes Verhalten**
Korrekter item name

**Screenshots**
![Screenshot_2020-05-12-14-27-50-474_com fastemulator gba](https://user-images.githubusercontent.com/65133519/81691503-375e0780-945d-11ea-9c80-90fdba3bc5b1.jpg)

**Verwendeter Emulator / Hardware**
MyBoy für Android

**Zusätzliche Information**

Ich schätze mal das item sollte eine Granabeere sein. Ich wüsste nicht wann ich davor eine bekommen habe sollte. Kann mich auch irren

**Comment by 4Reddy** [comment]
Obwohl, es steht Items dort.
Ich glaube es ist die Wundersaat die ich im Items beutel habe.
Da weiß ich nämlich auch nicht wann ich die bekommen haben sollte

**Comment by SBird1337** [comment]
Nope, die Wundersaat hast du im Wald von Yelnia gefunden, diese Items werden dir im Beutel net angezeigt, weil sie nicht existieren.
