### ISSUE TITLE
Alle verbugten Minisprites

### ISSUE THREAD

**Issue by Dragonflysots** [pokemon-sots/pokemon-sots-issues#45]
**Beschreibe den Bug**
*Eine klare Beschreibung, was genau der Bug ist.*

**Reproduzieren**
*Schritte, um den Bug auszulösen*
Öffne das PKMN Menu, dann sind manche Minisprites verbugt.

**Erwartetes Verhalten**
Richtige Darstellung der Farben.

**Screenshots**
*![verbuggte minisprites](https://user-images.githubusercontent.com/27623565/81702411-86129e00-946b-11ea-9fc6-578955a0e23b.png)*

**Verwendeter Emulator / Hardware**
Egal, ist bei jedem gleich.

**Comment by SBird1337** [comment]
supersedes #34 and #36

**Comment by Dragonflysots** [comment]
Sollte nun alles gefixt sein.
