### ISSUE TITLE
Hairstyle of male Hiro flipped horizontally when running

### ISSUE THREAD

**Issue by WodkaRHR** [pokemon-sots/pokemon-sots-issues#6]
*Bitte fülle dieses Template aus, und lösche vor dem Abschicken die Platzhalter, sowie diese Zeile.*

**Beschreibe den Bug**
Nutzt man B zum Rennen, wird die Frisur des männlichen Helden horizontal geflippt.

**Reproduzieren**
*Schritte, um den Bug auszulösen*
Mit dem männlichen Charakter rennen (B-Taste).

**Erwartetes Verhalten**
Konsistente Frisur.

**Screenshots**
n/a

**Verwendeter Emulator / Hardware**
mGBA

**Zusätzliche Information**
n/a

**Comment by Dragonflysots** [comment]
Also bisher hat es wohl keinen anderen gestört, wir sehen das auch nicht als Problem, sieht eher gut aus.^^
