### ISSUE TITLE
Layer mismatch when colliding with higher plattform

### ISSUE THREAD

**Issue by WodkaRHR** [pokemon-sots/pokemon-sots-issues#8]
*Bitte fülle dieses Template aus, und lösche vor dem Abschicken die Platzhalter, sowie diese Zeile.*

**Beschreibe den Bug**
Kollidiert man mit einem bestimmten Tile, existiert ein Frame, indem ein Teil des Arms vom OAM auf der Plattform sichtbar wird.

**Reproduzieren**
Südlich mit dem Tile kollidieren.

**Erwartetes Verhalten**
Verdeckter Arm.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/13219625/81511620-eb0aae80-931a-11ea-8157-3dfaf2f6a47c.png)

**Verwendeter Emulator / Hardware**
mGBA

**Zusätzliche Information**
n/a

**Comment by ipatix** [comment]
Mhm, ich dachte das hätte ich vor dem Prerelease schon entdeckt.

**Comment by Dragonflysots** [comment]
Ich dachte ich hätte es gefixt, hmm hab wohl nur den layer erwischt nicht die andere Map. Wird dann demnächst gefixt, danke. :D
