### ISSUE TITLE
Gras vor heilenden Kristal in Wald Stadt

### ISSUE THREAD

**Issue by 4Reddy** [pokemon-sots/pokemon-sots-issues#80]
**Beschreibe den Bug**
Wenn man vor dem Kristall steht ist unter einem gras, obwohl da keines sein sollte

**Reproduzieren**
*Schritte, um den Bug auszulösen*
1. Befinde dich im Arc nachden die energie aus dem baum gestohlen wurde
2. Gehe in die Wald Stadt
3. Stelle dich vor dem Kristall

**Erwartetes Verhalten**
Kein gras

**Screenshots**
![Screenshot_2020-05-13-19-51-57-895_com fastemulator gba](https://user-images.githubusercontent.com/65133519/81847227-99009d80-9553-11ea-8e10-fb23a6f48159.jpg)
![Screenshot_2020-05-13-19-52-03-226_com fastemulator gba](https://user-images.githubusercontent.com/65133519/81847240-9c942480-9553-11ea-9be8-a7e8763d686c.jpg)

**Verwendeter Emulator / Hardware**
MyBoy für Android

**Zusätzliche Information**
/

**Comment by Dragonflysots** [comment]
Bereits gefixt.
