### ISSUE TITLE
Durchlässige Wand

### ISSUE THREAD

**Issue by xydragonxy** [pokemon-sots/pokemon-sots-issues#91]
**Beschreibe den Bug**
Im Wald von Yelnia direkt am Anfang ist eine Lücke in der Wand in die ich mich reinstellen kann. 

**Reproduzieren**

1. Gehe nach Yelnia-Wald
2. Gehe zum Punkt wo der Charackter steht.
3. Dieser Punkt sollte nich erreichbar sein.

**Erwartetes Verhalten**
Sollte nicht begehbar sein.

**Screenshots**
![Wand1](https://user-images.githubusercontent.com/65260349/81873122-58b51580-957b-11ea-9339-ac095823c0fb.PNG)

**Verwendeter Emulator / Hardware**
mgba 0.8.1
**Zusätzliche Information**
N/A

**Comment by Dragonflysots** [comment]
Wieso sind deine Screenshots so dunkel. xD Nutz doch die Screenshotsfunktion vom Emulator, vielleicht die Heiligkeit ja besser, man sieht ja nichts haha. Aber ja ich erkenne es trotzdem, danke. :D

**Comment by xLiviusx** [comment]
So besser?

![ersatz](https://user-images.githubusercontent.com/65140155/81874282-db3ed480-957d-11ea-9d04-953f113bd8f9.JPG)
