### ISSUE TITLE
Komischer Grasfleck

### ISSUE THREAD

**Issue by xydragonxy** [pokemon-sots/pokemon-sots-issues#98]
**Beschreibe den Bug**
Wenn man vor den Heilkristall in Sylviria City steht erschein ein kleines Grasfeld unter den Füßen. Dieses war vorher nicht ersichtlich.

**Reproduzieren**

1. Stelle dich unter den Kristall in Sylviria City am Pokecenter.
2. Unter dem Spieler taucht ein Grasfeld auf das vorher nicht zu sehen war.

**Erwartetes Verhalten**
Das Feld sollte so aussehen wie auf den anderen Feldern in der umgebung und sich nicht zu einem Grasfeld verändern

**Screenshots**
![Kristall](https://user-images.githubusercontent.com/65260349/81945458-6f508080-95fe-11ea-99e7-45ada41d5ff4.PNG)

**Verwendeter Emulator / Hardware**
mgba 0.8.1

**Zusätzliche Information**
N/A

**Comment by Dragonflysots** [comment]
Bereits gefixt.

**Comment by xydragonxy** [comment]
okay hätte vorher schauen sollen sry :)

**Comment by Dragonflysots** [comment]
Nö kein Problem, dafür bin ich ja da. :D
