### ISSUE TITLE
Itemlager auf Englisch

### ISSUE THREAD

**Issue by OneThoughCookie** [pokemon-sots/pokemon-sots-issues#99]
**Beschreibe den Bug**
Das Itemlager ist auf Englisch

**Erwartetes Verhalten**
Sollte auf Deutsch sein

**Screenshots**
![pokeemerald-0](https://user-images.githubusercontent.com/62719633/81992416-b01eb880-9643-11ea-81db-81628af17395.png)

**Verwendeter Emulator / Hardware**
mGBA

**Comment by Dragonflysots** [comment]
Bereits gefixt.

**Comment by SBird1337** [comment]
duplicate of #77
